Pull request #2487: FL-10091:  Fixed app-editors/vim autogen and updated the templates
Merge in CORE/kit-fixups from ~ADBOSCO/kit-fixups:FL-10660 to master

Squashed commit of the following:

commit 8765a223293916a19450bec7bb4331c12fdb6114
Author: Adriano Dal Bosco <adbosco15@gmail.com>
Date:   Wed Nov 2 06:58:22 2022 +0000

    Updated the vim-core, vim and gvim templates.

    Most of the changes in the new ebuilds from Gentoo were cosmetic, or
    meant to make the bash code slightly more correct.

    There has also been changes in the eclasses inherited and in consequence
    some of the code in the ebuild (e.g. gnome2 vs xdg).  Overall these
    changes made the ebuilds slightly simpler.

    I also moved some of the files in the vim/files directory to
    vim-core/files or gvim/files, according to the package that actually
    uses them.

commit cb5fbd0cca35cda81895e5103ef54d2dcf7f9033
Author: Adriano Dal Bosco <adbosco15@gmail.com>
Date:   Wed Nov 2 06:52:45 2022 +0000

    Fixed app-editors/vim autogen

    The autogen was failing because of new ill bahaved tags. Filtered
    out the bad tags with regexp.

    The vim ebuild from Gentoo had a patch set.  Added those to the
    appropriate files dir and listed the patches in the autogen.

diff --git a/editors-kit/curated/app-editors/vim/templates/gvim.tmpl b/editors-kit/curated/app-editors/vim/templates/gvim.tmpl
--- a/editors-kit/curated/app-editors/vim/templates/gvim.tmpl
+++ b/editors-kit/curated/app-editors/vim/templates/gvim.tmpl
@@ -2,20 +2,25 @@
 
 EAPI=7
 VIM_VERSION="$(ver_cut 1-2)"
+LUA_COMPAT=( lua5-{1..4} luajit )
 PYTHON_COMPAT=( {{python_compat}} )
-inherit eutils vim-doc flag-o-matic fdo-mime gnome2-utils bash-completion-r1 prefix python-single-r1
+PYTHON_REQ_USE="threads(+)"
+
+inherit bash-completion-r1 flag-o-matic lua-single prefix python-single-r1 ruby-single toolchain-funcs vim-doc xdg-utils
 
 DESCRIPTION="GUI version of the Vim text editor"
 HOMEPAGE="http://www.vim.org/ https://github.com/vim/vim"
 SRC_URI="{{artifacts[0].src_uri}}"
+S="${WORKDIR}"/vim-${PV}
 
 SLOT="0"
 LICENSE="vim"
 KEYWORDS="*"
-IUSE="acl aqua cscope debug gnome gtk gtk3 lua luajit motif neXt netbeans nls perl python racket ruby selinux session tcl"
+IUSE="acl aqua crypt cscope debug lua minimal motif netbeans nls perl python racket ruby selinux session sound tcl"
 REQUIRED_USE="
-	luajit? ( lua )
+	lua? ( ${LUA_REQUIRED_USE} )
 	python? ( ${PYTHON_REQUIRED_USE} )
+	aqua? ( !motif )
 "
 
 RDEPEND="
@@ -28,62 +33,55 @@ RDEPEND="
 	x11-libs/libXt
 	acl? ( kernel_linux? ( sys-apps/acl ) )
 	!aqua? (
-		gtk3? (
+		motif? ( >=x11-libs/motif-2.3:0 )
+		!motif? (
 			x11-libs/gtk+:3
 			x11-libs/libXft
 		)
-		!gtk3? (
-			gtk? (
-				>=x11-libs/gtk+-2.6:2
-				x11-libs/libXft
-				gnome? ( >=gnome-base/libgnomeui-2.6 )
-			)
-			!gtk? (
-				motif? ( >=x11-libs/motif-2.3:0 )
-				!motif? (
-					neXt? ( x11-libs/neXtaw )
-					!neXt? ( x11-libs/libXaw )
-				)
-			)
-		)
 	)
+	crypt? ( dev-libs/libsodium:= )
 	cscope? ( dev-util/cscope )
 	lua? (
-		luajit? ( dev-lang/luajit:2= )
-		!luajit? ( dev-lang/lua:0[deprecated] )
+		${LUA_DEPS}
+		$(lua_gen_impl_dep 'deprecated' lua5-1)
 	)
 	nls? ( virtual/libintl )
 	perl? ( dev-lang/perl:= )
 	python? ( ${PYTHON_DEPS} )
 	racket? ( dev-scheme/racket )
-	ruby? ( dev-lang/ruby:= )
+	ruby? ( ${RUBY_DEPS} )
 	selinux? ( sys-libs/libselinux )
 	session? ( x11-libs/libSM )
+	sound? ( media-libs/libcanberra )
 	tcl? ( dev-lang/tcl:0= )
 "
-DEPEND="${RDEPEND}
-	dev-util/ctags
+
+DEPEND="${RDEPEND}"
+# configure runs the Lua interpreter
+BDEPEND="
 	sys-devel/autoconf
 	virtual/pkgconfig
+	lua? ( ${LUA_DEPS} )
 	nls? ( sys-devel/gettext )
 "
 
-S=${WORKDIR}/vim-${PV}
-
+{%- if patches %}
 PATCHES=(
 	{%- for patch in patches %}
 	"${FILESDIR}/{{patch}}"
 	{%- endfor %}
 )
+{%- endif %}
+
+# various failures (bugs #630042 and #682320)
+RESTRICT="test"
+
 pkg_setup() {
 	# people with broken alphabets run into trouble. bug 82186.
 	unset LANG LC_ALL
 	export LC_COLLATE="C"
 
-	# Gnome sandbox silliness. bug #114475.
-	mkdir -p "${T}"/home
-	export HOME="${T}"/home
-
+	use lua && lua-single_pkg_setup
 	use python && python-single-r1_pkg_setup
 }
 
@@ -91,17 +89,21 @@ src_prepare() {
 	default
 
 	# Fixup a script to use awk instead of nawk
-	sed -i '1s|.*|#!'"${EPREFIX}"'/usr/bin/awk -f|' "${S}"/runtime/tools/mve.awk \
-		|| die "mve.awk sed failed"
+	sed -i -e \
+		'1s|.*|#!'"${EPREFIX}"'/usr/bin/awk -f|' \
+		"${S}"/runtime/tools/mve.awk || die "mve.awk sed failed"
 
 	# Read vimrc and gvimrc from /etc/vim
-	echo '#define SYS_VIMRC_FILE "'${EPREFIX}'/etc/vim/vimrc"' >> "${S}"/src/feature.h
-	echo '#define SYS_GVIMRC_FILE "'${EPREFIX}'/etc/vim/gvimrc"' >> "${S}"/src/feature.h
+	echo '#define SYS_VIMRC_FILE "'${EPREFIX}'/etc/vim/vimrc"' \
+	    >> "${S}"/src/feature.h || die "echo failed"
+	echo '#define SYS_GVIMRC_FILE "'${EPREFIX}'/etc/vim/gvimrc"' \
+	    >> "${S}"/src/feature.h || die "echo failed"
 
 	# Use exuberant ctags which installs as /usr/bin/exuberant-ctags.
 	# Hopefully this pattern won't break for a while at least.
 	# This fixes bug 29398 (27 Sep 2003 agriffis)
-	sed -i 's/\<ctags\("\| [-*.]\)/exuberant-&/g' \
+	sed -i -e \
+		's/\<ctags\("\| [-*.]\)/exuberant-&/g' \
 		"${S}"/runtime/doc/syntax.txt \
 		"${S}"/runtime/doc/tagsrch.txt \
 		"${S}"/runtime/doc/usr_29.txt \
@@ -111,32 +113,44 @@ src_prepare() {
 	# Don't be fooled by /usr/include/libc.h.  When found, vim thinks
 	# this is NeXT, but it's actually just a file in dev-libs/9libs
 	# This fixes bug 43885 (20 Mar 2004 agriffis)
-	sed -i 's/ libc\.h / /' "${S}"/src/configure.ac || die 'sed failed'
+	sed -i -e \
+		's/ libc\.h / /' "${S}"/src/configure.ac || die 'sed failed'
 
 	# gcc on sparc32 has this, uhm, interesting problem with detecting EOF
 	# correctly. To avoid some really entertaining error messages about stuff
 	# which isn't even in the source file being invalid, we'll do some trickery
 	# to make the error never occur. bug 66162 (02 October 2004 ciaranm)
-	find "${S}" -name '*.c' | while read c ; do echo >> "$c" ; done
-
-	# Try to avoid sandbox problems. Bug #114475.
-	if [[ -d "${S}"/src/po ]] ; then
-		sed -i '/-S check.vim/s,..VIM.,ln -s $(VIM) testvim \; ./testvim -X,' \
-			"${S}"/src/po/Makefile
+	if [[ -d "${S}"/src/po ]]; then
+		sed -i -e \
+			'/-S check.vim/s,..VIM.,ln -s $(VIM) testvim \; ./testvim -X,' \
+			"${S}"/src/po/Makefile || die
 	fi
 
-	cp "${S}"/src/config.mk.dist "${S}"/src/auto/config.mk
+	cp -v "${S}"/src/config.mk.dist "${S}"/src/auto/config.mk || die "Failed to copy config.mk."
 
-	# Bug #378.17 - Build properly with >=perl-core/ExtUtils-ParseXS-3.20.0
-	sed -i "s:\\\$(PERLLIB)/ExtUtils/xsubpp:${EPREFIX}/usr/bin/xsubpp:"	\
+	# Bug #378107 - Build properly with >=perl-core/ExtUtils-ParseXS-3.20.0
+	sed -i -e \
+		"s:\\\$(PERLLIB)/ExtUtils/xsubpp:${EPREFIX}/usr/bin/xsubpp:" \
 		"${S}"/src/Makefile || die 'sed for ExtUtils-ParseXS failed'
 
-	eapply_user
+	# Fix bug 18245: Prevent "make" from the following chain:
+	# (1) Notice configure.ac is newer than auto/configure
+	# (2) Rebuild auto/configure
+	# (3) Notice auto/configure is newer than auto/config.mk
+	# (4) Run ./configure (with wrong args) to remake auto/config.mk
+	sed -i -e \
+		's# auto/config\.mk:#:#' src/Makefile || die "Makefile sed failed"
+	rm -v src/auto/configure || die "rm failed"
+
+	# --with-features=huge forces on cscope even if we --disable it. We need
+	# to sed this out to avoid screwiness. (1 Sep 2004 ciaranm)
+	if ! use cscope; then
+		sed -i -e \
+			'/# define FEAT_CSCOPE/d' src/feature.h || die "couldn't disable cscope"
+	fi
 }
 
 src_configure() {
-	local myconf=()
-
 	# Fix bug 37354: Disallow -funroll-all-loops on amd64
 	# Bug 57859 suggests that we want to do this for all archs
 	filter-flags -funroll-all-loops
@@ -146,34 +160,32 @@ src_configure() {
 	# multiple archs...
 	replace-flags -O3 -O2
 
-	# Fix bug 18245: Prevent "make" from the following chain:
-	# (1) Notice configure.ac is newer than auto/configure
-	# (2) Rebuild auto/configure
-	# (3) Notice auto/configure is newer than auto/config.mk
-	# (4) Run ./configure (with wrong args) to remake auto/config.mk
-	sed -i 's# auto/config\.mk:#:#' src/Makefile || die "Makefile sed failed"
-	rm -f src/auto/configure
 	emake -j1 -C src autoconf
 
 	# This should fix a sandbox violation (see bug 24447). The hvc
 	# things are for ppc64, see bug 86433.
-	for file in /dev/pty/s* /dev/console /dev/hvc/* /dev/hvc* ; do
-		[[ -e ${file} ]] && addwrite $file
+	local file
+	for file in /dev/pty/s* /dev/console /dev/hvc/* /dev/hvc*; do
+		if [[ -e ${file} ]]; then
+			addwrite $file
+		fi
 	done
 
 	use debug && append-flags "-DDEBUG"
 
-	myconf=(
+	local myconf=(
 		--with-features=huge
 		--disable-gpm
-		--enable-multibyte
+		--with-gnome=no
+		$(use_enable sound canberra)
 		$(use_enable acl)
+		$(use_enable crypt libsodium)
 		$(use_enable cscope)
-		$(use_enable lua luainterp)
-		$(use_with luajit)
 		$(use_enable netbeans)
 		$(use_enable nls)
 		$(use_enable perl perlinterp)
+		$(use_enable python python3interp)
+		$(use_with python python3-command "${PYTHON}")
 		$(use_enable racket mzschemeinterp)
 		$(use_enable ruby rubyinterp)
 		$(use_enable selinux)
@@ -181,65 +193,33 @@ src_configure() {
 		$(use_enable tcl tclinterp)
 	)
 
-	if use python ; then
-		local v
+	if use lua; then
+		# -DLUA_COMPAT_OPENLIB=1 is required to enable the
+		# deprecated (in 5.1) luaL_openlib API (#874690)
+		use lua_single_target_lua5-1 && append-cppflags -DLUA_COMPAT_OPENLIB=1
 
-		[[ ${EPYTHON} == python3* ]] && v=3
 		myconf+=(
-			--enable-python${v}interp
-			vi_cv_path_python${v}="${PYTHON}"
-		)
-	else
-		myconf+=(
-			--disable-pythoninterp
-			--disable-python3interp
+			--enable-luainterp
+			$(use_with lua_single_target_luajit luajit)
+			--with-lua-prefix="${EPREFIX}/usr"
 		)
 	fi
 
-	# --with-features=huge forces on cscope even if we --disable it. We need
-	# to sed this out to avoid screwiness. (1 Sep 2004 ciaranm)
-	if ! use cscope ; then
-		sed -i '/# define FEAT_CSCOPE/d' src/feature.h || \
-			die "couldn't disable cscope"
-	fi
-
-	# gvim's GUI preference order is as follows:
-	# aqua					 CARBON (not tested)
-	# -aqua gtk3				GTK3
-	# -aqua -gtk3 gnome		   GNOME2
-	# -aqua -gtk3 -gnome gtk	   GTK2
-	# -aqua -gtk -gtk3 motif	   MOTIF
-	# -aqua -gtk -gtk3 -motif neXt  NEXTAW
-	# -aqua -gtk -gtk3 -motif -neXt ATHENA
+	# Default is gtk unless aqua or motif are enabled
 	echo ; echo
-	if use aqua ; then
+	if use aqua; then
 		einfo "Building gvim with the Carbon GUI"
 		myconf+=(
 			--enable-darwin
 			--enable-gui=carbon
 		)
-	elif use gtk3 ; then
+	elif use motif; then
+		einfo "Building gvim with the MOTIF GUI"
+		myconf+=( --enable-gui=motif )
+	else
 		myconf+=( --enable-gtk3-check )
 		einfo "Building gvim with the gtk+-3 GUI"
 		myconf+=( --enable-gui=gtk3 )
-	elif use gtk ; then
-		myconf+=( --enable-gtk2-check )
-		if use gnome ; then
-			einfo "Building gvim with the Gnome 2 GUI"
-			myconf+=( --enable-gui=gnome2 )
-		else
-			einfo "Building gvim with the gtk+-2 GUI"
-			myconf+=( --enable-gui=gtk2 )
-		fi
-	elif use motif ; then
-		einfo "Building gvim with the MOTIF GUI"
-		myconf+=( --enable-gui=motif )
-	elif use neXt ; then
-		einfo "Building gvim with the neXtaw GUI"
-		myconf+=( --enable-gui=nextaw )
-	else
-		einfo "Building gvim with the Athena GUI"
-		myconf+=( --enable-gui=athena )
 	fi
 	echo ; echo
 
@@ -271,14 +251,14 @@ src_compile() {
 }
 
 src_test() {
-	echo
+	einfo
 	einfo "Starting vim tests. Several error messages will be shown"
 	einfo "while the tests run. This is normal behaviour and does not"
 	einfo "indicate a fault."
-	echo
+	einfo
 	ewarn "If the tests fail, your terminal may be left in a strange"
 	ewarn "state. Usually, running 'reset' will fix this."
-	echo
+	einfo
 
 	# Don't let vim talk to X
 	unset DISPLAY
@@ -288,45 +268,18 @@ src_test() {
 	ln -s "${S}"/src/gvim "${S}"/src/testvim || die
 
 	# Make sure our VIMPROG is used.
-	sed -i 's:\.\./vim:../testvim:' src/testdir/test49.vim || die
+	sed -i -e 's:\.\./vim:../testvim:' src/testdir/test49.vim || die
 
 	# Don't do additional GUI tests.
 	emake -j1 VIMPROG=../testvim -C src/testdir nongui
 }
 
-# Make convenience symlinks, hopefully without stepping on toes.  Some
-# of these links are "owned" by the vim ebuild when it is installed,
-# but they might be good for gvim as well (see bug 45828)
-update_vim_symlinks() {
-	local f syms
-	syms="vimdiff rvim rview"
-	einfo "Calling eselect vi update..."
-	# Call this with --if-unset to respect user's choice (bug 187449)
+# Call eselect vi update with --if-unset
+# to respect user's choice (bug 187449)
+eselect_vi_update() {
+	ebegin "Calling eselect vi update"
 	eselect vi update --if-unset
-
-	# Make or remove convenience symlink, vim -> gvim
-	if [[ -f "${EROOT}"/usr/bin/gvim ]]; then
-		ln -s gvim "${EROOT}"/usr/bin/vim 2>/dev/null
-	elif [[ -L "${EROOT}"/usr/bin/vim && ! -f "${EROOT}"/usr/bin/vim ]]; then
-		rm "${EROOT}"/usr/bin/vim
-	fi
-
-	# Make or remove convenience symlinks to vim
-	if [[ -f "${EROOT}"/usr/bin/vim ]]; then
-		for f in ${syms}; do
-			ln -s vim "${EROOT}"/usr/bin/${f} 2>/dev/null
-		done
-	else
-		for f in ${syms}; do
-			if [[ -L "${EROOT}"/usr/bin/${f} && ! -f "${EROOT}"/usr/bin/${f} ]]; then
-				rm -f "${EROOT}"/usr/bin/${f}
-			fi
-		done
-	fi
-
-	# This will still break if you merge then remove the vi package,
-	# but there's only so much you can do, eh?  Unfortunately we don't
-	# have triggers like are done in rpm-land.
+	eend $?
 }
 
 src_install() {
@@ -343,47 +296,51 @@ src_install() {
 	emake -C src DESTDIR="${D}" DATADIR="${EPREFIX}"/usr/share install-icons
 
 	dodir /usr/share/man/man1
-	echo ".so vim.1" > "${ED}"/usr/share/man/man1/gvim.1
-	echo ".so vim.1" > "${ED}"/usr/share/man/man1/gview.1
-	echo ".so vimdiff.1" > "${ED}"/usr/share/man/man1/gvimdiff.1
+	echo ".so vim.1" > "${ED}"/usr/share/man/man1/gvim.1 || die "echo failed"
+	echo ".so vim.1" > "${ED}"/usr/share/man/man1/gview.1 || die "echo failed"
+	echo ".so vimdiff.1" > "${ED}"/usr/share/man/man1/gvimdiff.1 || die "echo failed"
 
 	insinto /etc/vim
 	newins "${FILESDIR}"/gvimrc-r1 gvimrc
 	eprefixify "${ED}"/etc/vim/gvimrc
 
-	doicon -s scalable "${FILESDIR}"/gvim.svg
-
 	# bash completion script, bug #79018.
 	newbashcomp "${FILESDIR}"/${PN}-completion ${PN}
+	bashcomp_alias ${PN} gvimdiff
+	bashcomp_alias ${PN} evim
+	bashcomp_alias ${PN} eview
+	bashcomp_alias ${PN} gview
+	bashcomp_alias ${PN} rgvim
+	bashcomp_alias ${PN} rgview
 
 	# don't install vim desktop file
-	rm "${ED}"/usr/share/applications/vim.desktop || die "failed to remove vim.desktop"
+	rm -v "${ED}"/usr/share/applications/vim.desktop || die "failed to remove vim.desktop"
 }
 
 pkg_postinst() {
-	# Update documentation tags (from vim-doc.eclass)
+	# update documentation tags (from vim-doc.eclass)
 	update_vim_helptags
 
-	# Update fdo mime stuff, bug #78394
-	fdo-mime_desktop_database_update
+	# update fdo mime stuff, bug #78394
+	xdg_desktop_database_update
 
-	# Update icon cache
-	gnome2_icon_cache_update
+	# update icon cache
+	xdg_icon_cache_update
 
-	# Make convenience symlinks
-	update_vim_symlinks
+	# call eselect vi update
+	eselect_vi_update
 }
 
 pkg_postrm() {
-	# Update documentation tags (from vim-doc.eclass)
+	# update documentation tags (from vim-doc.eclass)
 	update_vim_helptags
 
-	# Update fdo mime stuff, bug #78394
-	fdo-mime_desktop_database_update
+	# update fdo mime stuff, bug #78394
+	xdg_desktop_database_update
 
-	# Update icon cache
-	gnome2_icon_cache_update
+	# update icon cache
+	xdg_icon_cache_update
 
-	# Make convenience symlinks
-	update_vim_symlinks
+	# call eselect vi update
+	eselect_vi_update
 }
diff --git a/editors-kit/curated/app-editors/vim/templates/vim-core.tmpl b/editors-kit/curated/app-editors/vim/templates/vim-core.tmpl
--- a/editors-kit/curated/app-editors/vim/templates/vim-core.tmpl
+++ b/editors-kit/curated/app-editors/vim/templates/vim-core.tmpl
@@ -2,44 +2,46 @@
 
 EAPI=7
 VIM_VERSION="$(ver_cut 1-2)"
-inherit eutils vim-doc flag-o-matic bash-completion-r1 prefix
+inherit bash-completion-r1 desktop flag-o-matic prefix vim-doc xdg-utils
 
 DESCRIPTION="Vim and GVim shared files"
 HOMEPAGE="http://www.vim.org/ https://github.com/vim/vim"
 SRC_URI="{{artifacts[0].src_uri}}"
+S=${WORKDIR}/vim-${PV}
 
 SLOT="0"
 LICENSE="vim"
 KEYWORDS="*"
 IUSE="nls acl minimal"
 
-DEPEND="sys-devel/autoconf"
-PDEPEND="!minimal? ( app-vim/gentoo-syntax )"
+# ncurses is only needed by ./configure, so no subslot operator required
+DEPEND=">=sys-libs/ncurses-5.2-r2:0"
+BDEPEND="sys-devel/autoconf"
 
-S=${WORKDIR}/vim-${PV}
-
+{%- if patches %}
 PATCHES=(
 	{%- for patch in patches %}
 	"${FILESDIR}/{{patch}}"
 	{%- endfor %}
 )
-
+{%- endif %}
 
 pkg_setup() {
 	# people with broken alphabets run into trouble. bug 82186.
 	unset LANG LC_ALL
 	export LC_COLLATE="C"
-
-	# Gnome sandbox silliness. bug #114475.
-	mkdir -p "${T}"/home
-	export HOME="${T}"/home
 }
 
 src_prepare() {
 	default
 
 	# Fixup a script to use awk instead of nawk
-	sed -i '1s|.*|#!'"${EPREFIX}"'/usr/bin/awk -f|' "${S}"/runtime/tools/mve.awk || die "mve.awk sed failed"
+	sed -i \
+		-e '1s|.*|#!'"${EPREFIX}"'/usr/bin/awk -f|' \
+		"${S}"/runtime/tools/mve.awk || die "sed failed"
+
+	# See bug #77841. We remove this file after the tarball extraction.
+	rm -v "${S}"/runtime/tools/vimspell.sh || die "rm failed"
 
 	# Read vimrc and gvimrc from /etc/vim
 	echo '#define SYS_VIMRC_FILE "'${EPREFIX}'/etc/vim/vimrc"' >> "${S}"/src/feature.h
@@ -64,7 +66,9 @@ src_prepare() {
 	# correctly. To avoid some really entertaining error messages about stuff
 	# which isn't even in the source file being invalid, we'll do some trickery
 	# to make the error never occur. bug 66162 (02 October 2004 ciaranm)
-	find "${S}" -name '*.c' | while read c ; do echo >> "$c" ; done
+	find "${S}" -name '*.c' | while read c; do
+		echo >> "$c" || die "echo failed"
+	done
 
 	# Try to avoid sandbox problems. Bug #114475.
 	if [[ -d "${S}"/src/po ]] ; then
@@ -73,61 +77,64 @@ src_prepare() {
 			"${S}"/src/po/Makefile
 	fi
 
-	cp "${S}"/src/config.mk.dist "${S}"/src/auto/config.mk
+	cp "${S}"/src/config.mk.dist "${S}"/src/auto/config.mk || die "Failed to copy config.mk"
 
 	# Bug #378.17 - Build properly with >=perl-core/ExtUtils-ParseXS-3.20.0
 	sed -i "s:\\\$(PERLLIB)/ExtUtils/xsubpp:${EPREFIX}/usr/bin/xsubpp:"	\
 		"${S}"/src/Makefile || die 'sed for ExtUtils-ParseXS failed'
 
-	eapply_user
-}
-
-src_configure() {
-	local myconf
-
-	# Fix bug 37354: Disallow -funroll-all-loops on amd64
-	# Bug 57859 suggests that we want to do this for all archs
-	filter-flags -funroll-all-loops
-
-	# Fix bug 76331: -O3 causes problems, use -O2 instead. We'll do this for
+	# Fix bug #76331: -O3 causes problems, use -O2 instead. We'll do this for
 	# everyone since previous flag filtering bugs have turned out to affect
 	# multiple archs...
 	replace-flags -O3 -O2
 
-	# Fix bug 18245: Prevent "make" from the following chain:
+	# Fix bug #18245: Prevent "make" from the following chain:
 	# (1) Notice configure.ac is newer than auto/configure
 	# (2) Rebuild auto/configure
 	# (3) Notice auto/configure is newer than auto/config.mk
 	# (4) Run ./configure (with wrong args) to remake auto/config.mk
 	sed -i 's# auto/config\.mk:#:#' src/Makefile || die "Makefile sed failed"
-	rm -f src/auto/configure
+
+	# Remove src/auto/configure file.
+	rm -v src/auto/configure || die "rm configure failed"
+}
+
+src_configure() {
+	# Fix bug 37354: Disallow -funroll-all-loops on amd64
+	# Bug 57859 suggests that we want to do this for all archs
+	filter-flags -funroll-all-loops
+
 	emake -j1 -C src autoconf
 
 	# This should fix a sandbox violation (see bug 24447). The hvc
 	# things are for ppc64, see bug 86433.
-	for file in /dev/pty/s* /dev/console /dev/hvc/* /dev/hvc* ; do
-		[[ -e ${file} ]] && addwrite $file
+	for file in /dev/pty/s* /dev/console /dev/hvc/* /dev/hvc*; do
+		if [[ -e "${file}" ]]; then
+			addwrite ${file}
+		fi
 	done
 
 	# Let Portage do the stripping. Some people like that.
 	export ac_cv_prog_STRIP="$(type -P true ) faking strip"
 
-	# Keep Gentoo Prefix env contained within the EPREFIX
-	use prefix && myconf+=" --without-local-dir"
+	local myconf=(
+		--with-modified-by=Funtoo-${PVR}
+		--enable-gui=no
+		--without-x
+		--disable-darwin
+		--disable-perlinterp
+		--disable-pythoninterp
+		--disable-rubyinterp
+		--disable-gpm
+		--disable-selinux
+		$(use_enable nls)
+		$(use_enable acl)
+	)
 
-	econf \
-		--with-modified-by=Funtoo-${PVR} \
-		--enable-gui=no \
-		--without-x \
-		--disable-darwin \
-		--disable-perlinterp \
-		--disable-pythoninterp \
-		--disable-rubyinterp \
-		--disable-gpm \
-		--disable-selinux \
-		$(use_enable nls) \
-		$(use_enable acl) \
-		${myconf}
+	# Keep Gentoo Prefix env contained within the EPREFIX
+	use prefix && myconf+=( --without-local-dir )
+
+	econf "${myconf[@]}"
 }
 
 src_compile() {
@@ -167,41 +174,41 @@ src_install() {
 	if use minimal ; then
 		# To save space, install only a subset of the files.
 		# Helps minimalize the livecd, bug 65144.
-		eshopts_push -s extglob
+		rm -rv "${ED}${vimfiles}"/{compiler,doc,ftplugin,indent} || die
+		rm -rv "${ED}${vimfiles}"/{macros,print,tools,tutor} || die
+		rm -v "${ED}"/usr/bin/vimtutor || die
 
-		rm -fr "${ED}${vimfiles}"/{compiler,doc,ftplugin,indent}
-		rm -fr "${ED}${vimfiles}"/{macros,print,tools,tutor}
-		rm "${ED}"/usr/bin/vimtutor
+		for f in "${ED}${vimfiles}"/colors/*.vim; do
+			if [[ ${f} != */@(default).vim ]] ; then
+				printf '%s\0' "${f}"
+			fi
+		done | xargs -0 rm -f || die
 
-		local keep_colors="default"
-		ignore=$(rm -fr "${ED}${vimfiles}"/colors/!(${keep_colors}).vim )
-
-		local keep_syntax="conf|crontab|fstab|inittab|resolv|sshdconfig"
-		# tinkering with the next line might make bad things happen ...
-		keep_syntax="${keep_syntax}|syntax|nosyntax|synload"
-		ignore=$(rm -fr "${ED}${vimfiles}"/syntax/!(${keep_syntax}).vim )
-
-		eshopts_pop
+		for f in "${ED}${vimfiles}"/syntax/*.vim; do
+			if [[ ${f} != */@(conf|crontab|fstab|inittab|resolv|sshdconfig|syntax|nosyntax|synload).vim ]] ; then
+				printf '%s\0' "${f}"
+			fi
+		done | xargs -0 rm -f || die
 	fi
-
-	# These files might have slight security issues, so we won't
-	# install them. See bug #77841. We don't mind if these don't
-	# exist.
-	rm "${ED}${vimfiles}"/tools/{vimspell.sh,tcltags} 2>/dev/null
 
 	newbashcomp "${FILESDIR}"/xxd-completion xxd
 
-	# We shouldn't be installing the ex or view man page symlinks, as they
-	# are managed by eselect-vi
-	rm -f "${ED}"/usr/share/man/man1/{ex,view}.1
+	# install gvim icon since both vim/gvim desktop files reference it
+	doicon -s scalable "${FILESDIR}"/gvim.svg
 }
 
 pkg_postinst() {
 	# Update documentation tags (from vim-doc.eclass)
 	update_vim_helptags
+
+	# update icon cache
+	xdg_icon_cache_update
 }
 
 pkg_postrm() {
 	# Update documentation tags (from vim-doc.eclass)
 	update_vim_helptags
+
+	# update icon cache
+	xdg_icon_cache_update
 }
diff --git a/editors-kit/curated/app-editors/vim/templates/vim.tmpl b/editors-kit/curated/app-editors/vim/templates/vim.tmpl
--- a/editors-kit/curated/app-editors/vim/templates/vim.tmpl
+++ b/editors-kit/curated/app-editors/vim/templates/vim.tmpl
@@ -2,8 +2,13 @@
 
 EAPI=7
 VIM_VERSION="$(ver_cut 1-2)"
+LUA_COMPAT=( lua5-{1..4} luajit )
 PYTHON_COMPAT=( {{python_compat}} )
-inherit eutils vim-doc flag-o-matic fdo-mime bash-completion-r1 python-single-r1
+PYTHON_REQ_USE="threads(+)"
+USE_RUBY="ruby27 ruby30 ruby31"
+
+inherit vim-doc flag-o-matic fdo-mime bash-completion-r1 python-single-r1 \
+		lua-single ruby-single toolchain-funcs desktop xdg-utils
 
 DESCRIPTION="Vim, an improved vi-style text editor"
 HOMEPAGE="http://www.vim.org/ https://github.com/vim/vim"
@@ -12,10 +17,11 @@ SRC_URI="{{artifacts[0].src_uri}}"
 SLOT="0"
 LICENSE="vim"
 KEYWORDS="*"
-IUSE="X acl cscope debug gpm lua luajit minimal nls perl python racket ruby selinux tcl vim-pager"
+IUSE="X acl crypt cscope debug gpm lua minimal nls perl python racket ruby selinux sound tcl terminal vim-pager"
 REQUIRED_USE="
-	luajit? ( lua )
+	lua? ( ${LUA_REQUIRED_USE} )
 	python? ( ${PYTHON_REQUIRED_USE} )
+	vim-pager? ( !minimal )
 "
 
 RDEPEND="
@@ -23,44 +29,45 @@ RDEPEND="
 	>=sys-libs/ncurses-5.2-r2:0=
 	nls? ( virtual/libintl )
 	acl? ( kernel_linux? ( sys-apps/acl ) )
+	crypt? ( dev-libs/libsodium:= )
 	cscope? ( dev-util/cscope )
 	gpm? ( >=sys-libs/gpm-1.19.3 )
-	lua? (
-	luajit? ( dev-lang/luajit:2= )
-		!luajit? ( dev-lang/lua:0[deprecated] )
+	lua? ( ${LUA_DEPS}
+		$(lua_gen_impl_dep 'deprecated' lua5-1)
 	)
-	!minimal? (
-		~app-editors/vim-core-${PV}
-		dev-util/ctags
-	)
+	~app-editors/vim-core-${PV}
+	!<app-editors/vim-core-8.2.4328-r1
+	vim-pager? ( app-editors/vim-core[-minimal] )
 	perl? ( dev-lang/perl:= )
 	python? ( ${PYTHON_DEPS} )
 	racket? ( dev-scheme/racket )
-	ruby? ( dev-lang/ruby:= )
+	ruby? ( ${RUBY_DEPS} )
 	selinux? ( sys-libs/libselinux )
+	sound? ( media-libs/libcanberra )
 	tcl? ( dev-lang/tcl:0= )
 	X? ( x11-libs/libXt )
 "
 DEPEND="${RDEPEND}
 	sys-devel/autoconf
+	lua? ( ${LUA_DEPS} )
 	nls? ( sys-devel/gettext )
 "
+PDEPEND="!minimal? ( app-vim/gentoo-syntax )"
 
+{%- if patches %}
 PATCHES=(
 	{%- for patch in patches %}
 	"${FILESDIR}/{{patch}}"
 	{%- endfor %}
 )
+{%- endif %}
 
 pkg_setup() {
 	# people with broken alphabets run into trouble. bug 82186.
 	unset LANG LC_ALL
 	export LC_COLLATE="C"
 
-	# Gnome sandbox silliness. bug #114475.
-	mkdir -p "${T}"/home
-	export HOME="${T}"/home
-
+	use lua && lua-single_pkg_setup
 	use python && python-single-r1_pkg_setup
 }
 
@@ -68,11 +75,15 @@ src_prepare() {
 	default
 
 	# Fixup a script to use awk instead of nawk
-	sed -i '1s|.*|#!'"${EPREFIX}"'/usr/bin/awk -f|' "${S}"/runtime/tools/mve.awk || die "mve.awk sed failed"
+	sed -i -e \
+		'1s|.*|#!'"${EPREFIX}"'/usr/bin/awk -f|' \
+		"${S}"/runtime/tools/mve.awk || die "mve.awk sed failed"
 
 	# Read vimrc and gvimrc from /etc/vim
-	echo '#define SYS_VIMRC_FILE "'${EPREFIX}'/etc/vim/vimrc"' >> "${S}"/src/feature.h
-	echo '#define SYS_GVIMRC_FILE "'${EPREFIX}'/etc/vim/gvimrc"' >> "${S}"/src/feature.h
+	echo '#define SYS_VIMRC_FILE "'${EPREFIX}'/etc/vim/vimrc"' \
+		>> "${S}"/src/feature.h || die "echo failed"
+	echo '#define SYS_GVIMRC_FILE "'${EPREFIX}'/etc/vim/gvimrc"' \
+		>> "${S}"/src/feature.h || die "echo failed"
 
 	# Use exuberant ctags which installs as /usr/bin/exuberant-ctags.
 	# Hopefully this pattern won't break for a while at least.
@@ -93,11 +104,13 @@ src_prepare() {
 	# correctly. To avoid some really entertaining error messages about stuff
 	# which isn't even in the source file being invalid, we'll do some trickery
 	# to make the error never occur. bug 66162 (02 October 2004 ciaranm)
-	find "${S}" -name '*.c' | while read c ; do echo >> "$c" ; done
+	find "${S}" -name '*.c' | while read c; do
+		echo >> "$c" || die "echo failed"
+	done
 
 	# conditionally make the manpager.sh script
-	if use vim-pager ; then
-		cat <<-END > "${S}"/runtime/macros/manpager.sh
+	if use vim-pager; then
+		cat > "${S}"/runtime/macros/manpager.sh <<-_EOF_ || die "cat EOF failed"
 			#!/bin/sh
 			sed -e 's/\x1B\[[[:digit:]]\+m//g' | col -b | \\
 					vim \\
@@ -105,22 +118,21 @@ src_prepare() {
 						-c 'set nolist nomod ft=man ts=8' \\
 						-c 'let g:showmarks_enable=0' \\
 						-c 'runtime! macros/less.vim' -
-			END
+			_EOF_
 	fi
 
 	# Try to avoid sandbox problems. Bug #114475.
-	if [[ -d "${S}"/src/po ]] ; then
-		sed -i '/-S check.vim/s,..VIM.,ln -s $(VIM) testvim \; ./testvim -X,' \
-		"${S}"/src/po/Makefile
+	if [[ -d "${S}"/src/po ]]; then
+		sed -i -e \
+			'/-S check.vim/s,..VIM.,ln -s $(VIM) testvim \; ./testvim -X,' \
+			"${S}"/src/po/Makefile || die "sed failed"
 	fi
 
-	cp "${S}"/src/config.mk.dist "${S}"/src/auto/config.mk
+	cp "${S}"/src/config.mk.dist "${S}"/src/auto/config.mk || die "Failed to copy config.mk."
 
 	# Bug #378.17 - Build properly with >=perl-core/ExtUtils-ParseXS-3.20.0
 	sed -i "s:\\\$(PERLLIB)/ExtUtils/xsubpp:${EPREFIX}/usr/bin/xsubpp:"	\
 		"${S}"/src/Makefile || die 'sed for ExtUtils-ParseXS failed'
-
-	eapply_user
 }
 
 src_configure() {
@@ -135,21 +147,17 @@ src_configure() {
 	# multiple archs...
 	replace-flags -O3 -O2
 
-	# Fix bug 18245: Prevent "make" from the following chain:
-	# (1) Notice configure.ac is newer than auto/configure
-	# (2) Rebuild auto/configure
-	# (3) Notice auto/configure is newer than auto/config.mk
-	# (4) Run ./configure (with wrong args) to remake auto/config.mk
-	sed -i 's# auto/config\.mk:#:#' src/Makefile || die "Makefile sed failed"
-	rm -f src/auto/configure
 	emake -j1 -C src autoconf
 
 	# This should fix a sandbox violation (see bug 24447). The hvc
 	# things are for ppc64, see bug 86433.
-	for file in /dev/pty/s* /dev/console /dev/hvc/* /dev/hvc* ; do
-		[[ -e ${file} ]] && addwrite $file
+	for file in /dev/pty/s* /dev/console /dev/hvc/* /dev/hvc*; do
+		if [[ -e "${file}" ]]; then
+			addwrite ${file}
+		fi
 	done
 
+	local myconf=()
 	if use minimal ; then
 		myconf=(
 			--with-features=tiny
@@ -173,40 +181,39 @@ src_configure() {
 
 		myconf=(
 			--with-features=huge
-			--enable-multibyte
+			$(use_enable sound canberra)
 			$(use_enable acl)
+			$(use_enable crypt libsodium)
 			$(use_enable cscope)
 			$(use_enable gpm)
-			$(use_enable lua luainterp)
-			$(usex lua "--with-lua-prefix=${EPREFIX}/usr" "")
-			$(use_with luajit)
 			$(use_enable nls)
 			$(use_enable perl perlinterp)
+			$(use_enable python python3interp)
+			$(use_with python python3-command "${PYTHON}")
 			$(use_enable racket mzschemeinterp)
 			$(use_enable ruby rubyinterp)
 			$(use_enable selinux)
 			$(use_enable tcl tclinterp)
+			$(use_enable terminal)
 		)
-
-		if use python ; then
-			local v
-			[[ ${EPYTHON} == python3* ]] && v=3
-			myconf+=(
-				--enable-python${v}interp
-				vi_cv_path_python${v}="${PYTHON}"
-			)
-		else
-			myconf+=(
-				--disable-pythoninterp
-				--disable-python3interp
-			)
-		fi
 
 		# --with-features=huge forces on cscope even if we --disable it. We need
 		# to sed this out to avoid screwiness. (1 Sep 2004 ciaranm)
 		if ! use cscope ; then
 			sed -i '/# define FEAT_CSCOPE/d' src/feature.h || \
 			die "couldn't disable cscope"
+		fi
+
+		if use lua; then
+			# -DLUA_COMPAT_OPENLIB=1 is required to enable the
+			# deprecated (in 5.1) luaL_openlib API (#874690)
+			use lua_single_target_lua5-1 && append-cppflags -DLUA_COMPAT_OPENLIB=1
+
+			myconf+=(
+				--enable-luainterp
+				$(use_with lua_single_target_luajit luajit)
+				--with-lua-prefix="${EPREFIX}/usr"
+			)
 		fi
 
 		# don't test USE=X here ... see bug #19115
@@ -237,63 +244,64 @@ src_compile() {
 }
 
 src_test() {
-	echo
+	einfo
 	einfo "Starting vim tests. Several error messages will be shown"
 	einfo "while the tests run. This is normal behaviour and does not"
 	einfo "indicate a fault."
-	echo
+	einfo
 	ewarn "If the tests fail, your terminal may be left in a strange"
 	ewarn "state. Usually, running 'reset' will fix this."
-	echo
+	einfo
 
 	# Don't let vim talk to X
 	unset DISPLAY
 
+	# Arch and opensuse seem to do this and at this point, I'm willing
+	# to try anything to avoid random test hangs!
+	export TERM=xterm
+
+	# See https://github.com/vim/vim/blob/f08b0eb8691ff09f98bc4beef986ece1c521655f/src/testdir/runtest.vim#L5
+	# for more information on test variables we can use.
+	# Note that certain variables need vim-compatible regex (not PCRE), see e.g.
+	# http://www.softpanorama.org/Editors/Vimorama/vim_regular_expressions.shtml.
+	#
+	# Skipped tests:
+	# - Test_expand_star_star
+	# Hangs because of a recursive symlink in /usr/include/nodejs (bug #616680)
+	# - Test_exrc
+	# Looks in wrong location? (bug #742710)
+	# - Test_job_tty_in_out
+	# Fragile and depends on TERM(?)
+	# - Test_spelldump_bang
+	# Hangs.
+	# - Test_fuzzy_completion_env
+	# Too sensitive to leaked environment variables.
+	# - Test_term_mouse_multiple_clicks_to_select_mode
+	# Hangs.
+	# - Test_spelldump
+	# Hangs.
+	export TEST_SKIP_PAT='\(Test_expand_star_star\|Test_exrc\|Test_job_tty_in_out\|Test_spelldump_bang\|Test_fuzzy_completion_env\|Test_term_mouse_multiple_clicks_to_select_mode\|Test_spelldump\)'
+
 	emake -j1 -C src/testdir nongui
 }
 
-# Make convenience symlinks, hopefully without stepping on toes.  Some
-# of these links are "owned" by the vim ebuild when it is installed,
-# but they might be good for gvim as well (see bug 45828)
-update_vim_symlinks() {
-	local f syms
-	syms="vimdiff rvim rview"
-	einfo "Calling eselect vi update..."
-	# Call this with --if-unset to respect user's choice (bug 187449)
+# Call eselect vi update with --if-unset
+# to respect user's choice (bug #187449)
+eselect_vi_update() {
+	ebegin "Calling eselect vi update"
 	eselect vi update --if-unset
-
-	# Make or remove convenience symlink, vim -> gvim
-	if [[ -f "${EROOT}"/usr/bin/gvim ]]; then
-		ln -s gvim "${EROOT}"/usr/bin/vim 2>/dev/null
-	elif [[ -L "${EROOT}"/usr/bin/vim && ! -f "${EROOT}"/usr/bin/vim ]]; then
-		rm "${EROOT}"/usr/bin/vim
-	fi
-
-	# Make or remove convenience symlinks to vim
-	if [[ -f "${EROOT}"/usr/bin/vim ]]; then
-		for f in ${syms}; do
-			ln -s vim "${EROOT}"/usr/bin/${f} 2>/dev/null
-		done
-	else
-		for f in ${syms}; do
-			if [[ -L "${EROOT}"/usr/bin/${f} && ! -f "${EROOT}"/usr/bin/${f} ]]; then
-				rm -f "${EROOT}"/usr/bin/${f}
-			fi
-		done
-	fi
-
-	# This will still break if you merge then remove the vi package,
-	# but there's only so much you can do, eh?	Unfortunately we don't
-	# have triggers like are done in rpm-land.
+	eend $?
 }
 
 src_install() {
 	local vimfiles=/usr/share/vim/vim${VIM_VERSION/.}
 
 	# Note: Do not install symlinks for 'vi', 'ex', or 'view', as these are
-	#	 managed by eselect-vi
+	#       managed by eselect-vi
 	dobin src/vim
-	dosym vim /usr/bin/vimdiff
+	if ! use minimal ; then
+		dosym vim /usr/bin/vimdiff
+	fi
 	dosym vim /usr/bin/rvim
 	dosym vim /usr/bin/rview
 	if use vim-pager ; then
@@ -304,29 +312,33 @@ src_install() {
 		fperms a+x ${vimfiles}/macros/manpager.sh
 	fi
 
+	domenu runtime/vim.desktop
+
 	newbashcomp "${FILESDIR}"/${PN}-completion ${PN}
+
 	# keep in sync with 'complete ... -F' list
 	bashcomp_alias vim ex vi view rvim rview vimdiff
-
-	# We shouldn't be installing the ex or view man page symlinks, as they
-	# are managed by eselect-vi
-	rm -f "${ED}"/usr/share/man/man1/{ex,view}.1
 }
 
 pkg_postinst() {
 	# Update documentation tags (from vim-doc.eclass)
 	update_vim_helptags
 
-	# Make convenience symlinks
-	update_vim_symlinks
+	# Call eselect vi update
+	eselect_vi_update
+
+	# update desktop file mime cache
+	xdg_desktop_database_update
 }
 
 pkg_postrm() {
 	# Update documentation tags (from vim-doc.eclass)
 	update_vim_helptags
 
-	# Make convenience symlinks
-	update_vim_symlinks
-}
+	# Call eselect vi update
+	eselect_vi_update
 
+	# update desktop file mime cache
+	xdg_desktop_database_update
+}
 
