Pull request #2196: FL-9956: Consolidate app-editors/vim autogen in curated.
Merge in CORE/kit-fixups from ~ALEX2101/kit-fixups:bugfix/FL-9956-vim-has-different-autogens-for-1.4-release-and-next to master

Squashed commit of the following:

commit 939e78f9a346b07f789eb6e00df09fcad151d9e8
Author: alex2101 <alex2101@gmail.com>
Date:   Wed Jul 20 13:20:52 2022 -0300

    FL-9956: Consolidate app-editors/vim autogen in curated.

diff --git a/editors-kit/curated/app-editors/vim/templates/gvim.tmpl b/editors-kit/curated/app-editors/vim/templates/gvim.tmpl
--- a/editors-kit/curated/app-editors/vim/templates/gvim.tmpl
+++ b/editors-kit/curated/app-editors/vim/templates/gvim.tmpl
@@ -1,26 +1,21 @@
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=6
+EAPI=7
+VIM_VERSION="$(ver_cut 1-2)"
 PYTHON_COMPAT=( {{python_compat}} )
-inherit eutils vim-doc flag-o-matic fdo-mime gnome2-utils versionator bash-completion-r1 prefix python-r1
-VIM_VERSION="$(get_version_component_range 1-2)"
-
-SRC_URI="https://github.com/vim/vim/archive/v${PV}.tar.gz -> vim-${PV}.tar.gz"
-KEYWORDS="*"
+inherit eutils vim-doc flag-o-matic fdo-mime gnome2-utils bash-completion-r1 prefix python-single-r1
 
 DESCRIPTION="GUI version of the Vim text editor"
 HOMEPAGE="http://www.vim.org/ https://github.com/vim/vim"
+SRC_URI="{{artifacts[0].src_uri}}"
 
 SLOT="0"
 LICENSE="vim"
+KEYWORDS="*"
 IUSE="acl aqua cscope debug gnome gtk gtk3 lua luajit motif neXt netbeans nls perl python racket ruby selinux session tcl"
 REQUIRED_USE="
 	luajit? ( lua )
-	python? (
-		|| ( $(python_gen_useflags '*') )
-		?? ( $(python_gen_useflags 'python2*') )
-		?? ( $(python_gen_useflags 'python3*') )
-	)
+	python? ( ${PYTHON_REQUIRED_USE} )
 "
 
 RDEPEND="
@@ -75,6 +70,11 @@ DEPEND="${RDEPEND}
 
 S=${WORKDIR}/vim-${PV}
 
+PATCHES=(
+	{%- for patch in patches %}
+	"${FILESDIR}/{{patch}}"
+	{%- endfor %}
+)
 pkg_setup() {
 	# people with broken alphabets run into trouble. bug 82186.
 	unset LANG LC_ALL
@@ -83,9 +83,13 @@ pkg_setup() {
 	# Gnome sandbox silliness. bug #114475.
 	mkdir -p "${T}"/home
 	export HOME="${T}"/home
+
+	use python && python-single-r1_pkg_setup
 }
 
 src_prepare() {
+	default
+
 	# Fixup a script to use awk instead of nawk
 	sed -i '1s|.*|#!'"${EPREFIX}"'/usr/bin/awk -f|' "${S}"/runtime/tools/mve.awk \
 		|| die "mve.awk sed failed"
@@ -121,15 +125,11 @@ src_prepare() {
 			"${S}"/src/po/Makefile
 	fi
 
-	if version_is_at_least 7.3.122 ; then
-		cp "${S}"/src/config.mk.dist "${S}"/src/auto/config.mk
-	fi
+	cp "${S}"/src/config.mk.dist "${S}"/src/auto/config.mk
 
 	# Bug #378.17 - Build properly with >=perl-core/ExtUtils-ParseXS-3.20.0
-	if version_is_at_least 7.3 ; then
-		sed -i "s:\\\$(PERLLIB)/ExtUtils/xsubpp:${EPREFIX}/usr/bin/xsubpp:"	\
-			"${S}"/src/Makefile || die 'sed for ExtUtils-ParseXS failed'
-	fi
+	sed -i "s:\\\$(PERLLIB)/ExtUtils/xsubpp:${EPREFIX}/usr/bin/xsubpp:"	\
+		"${S}"/src/Makefile || die 'sed for ExtUtils-ParseXS failed'
 
 	eapply_user
 }
@@ -182,17 +182,13 @@ src_configure() {
 	)
 
 	if use python ; then
-		py_add_interp() {
-			local v
+		local v
 
-			[[ ${EPYTHON} == python3* ]] && v=3
-			myconf+=(
-				--enable-python${v}interp
-				vi_cv_path_python${v}="${PYTHON}"
-			)
-		}
-
-		python_foreach_impl py_add_interp
+		[[ ${EPYTHON} == python3* ]] && v=3
+		myconf+=(
+			--enable-python${v}interp
+			vi_cv_path_python${v}="${PYTHON}"
+		)
 	else
 		myconf+=(
 			--disable-pythoninterp
@@ -261,7 +257,7 @@ src_configure() {
 	fi
 
 	econf \
-		--with-modified-by=Gentoo-${PVR} \
+		--with-modified-by=Funtoo-${PVR} \
 		--with-vim-name=gvim \
 		--with-x \
 		"${myconf[@]}"
diff --git a/editors-kit/curated/app-editors/vim/templates/vim-core.tmpl b/editors-kit/curated/app-editors/vim/templates/vim-core.tmpl
--- a/editors-kit/curated/app-editors/vim/templates/vim-core.tmpl
+++ b/editors-kit/curated/app-editors/vim/templates/vim-core.tmpl
@@ -1,29 +1,29 @@
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=6
-inherit eutils vim-doc flag-o-matic versionator bash-completion-r1 prefix
-VIM_VERSION="$(get_version_component_range 1-2)"
-
-if [[ ${PV} == 9999* ]] ; then
-	inherit git-r3
-	EGIT_REPO_URI="https://github.com/vim/vim.git"
-	EGIT_CHECKOUT_DIR=${WORKDIR}/vim-${PV}
-else
-	SRC_URI="https://github.com/vim/vim/archive/v${PV}.tar.gz -> vim-${PV}.tar.gz"
-	KEYWORDS="*"
-fi
+EAPI=7
+VIM_VERSION="$(ver_cut 1-2)"
+inherit eutils vim-doc flag-o-matic bash-completion-r1 prefix
 
 DESCRIPTION="Vim and GVim shared files"
 HOMEPAGE="http://www.vim.org/ https://github.com/vim/vim"
+SRC_URI="{{artifacts[0].src_uri}}"
 
 SLOT="0"
 LICENSE="vim"
+KEYWORDS="*"
 IUSE="nls acl minimal"
 
 DEPEND="sys-devel/autoconf"
 PDEPEND="!minimal? ( app-vim/gentoo-syntax )"
 
 S=${WORKDIR}/vim-${PV}
+
+PATCHES=(
+	{%- for patch in patches %}
+	"${FILESDIR}/{{patch}}"
+	{%- endfor %}
+)
+
 
 pkg_setup() {
 	# people with broken alphabets run into trouble. bug 82186.
@@ -36,6 +36,8 @@ pkg_setup() {
 }
 
 src_prepare() {
+	default
+
 	# Fixup a script to use awk instead of nawk
 	sed -i '1s|.*|#!'"${EPREFIX}"'/usr/bin/awk -f|' "${S}"/runtime/tools/mve.awk || die "mve.awk sed failed"
 
@@ -71,15 +73,11 @@ src_prepare() {
 			"${S}"/src/po/Makefile
 	fi
 
-	if version_is_at_least 7.3.122 ; then
-		cp "${S}"/src/config.mk.dist "${S}"/src/auto/config.mk
-	fi
+	cp "${S}"/src/config.mk.dist "${S}"/src/auto/config.mk
 
 	# Bug #378.17 - Build properly with >=perl-core/ExtUtils-ParseXS-3.20.0
-	if version_is_at_least 7.3 ; then
-		sed -i "s:\\\$(PERLLIB)/ExtUtils/xsubpp:${EPREFIX}/usr/bin/xsubpp:"	\
-			"${S}"/src/Makefile || die 'sed for ExtUtils-ParseXS failed'
-	fi
+	sed -i "s:\\\$(PERLLIB)/ExtUtils/xsubpp:${EPREFIX}/usr/bin/xsubpp:"	\
+		"${S}"/src/Makefile || die 'sed for ExtUtils-ParseXS failed'
 
 	eapply_user
 }
@@ -118,7 +116,7 @@ src_configure() {
 	use prefix && myconf+=" --without-local-dir"
 
 	econf \
-		--with-modified-by=Gentoo-${PVR} \
+		--with-modified-by=Funtoo-${PVR} \
 		--enable-gui=no \
 		--without-x \
 		--disable-darwin \
