[core-server-kit] autogen sys-libs/liburing

diff --git a/core-server-kit/autogen.kit.d/tools.yml b/core-server-kit/autogen.kit.d/tools.yml
--- a/core-server-kit/autogen.kit.d/tools.yml
+++ b/core-server-kit/autogen.kit.d/tools.yml
@@ -653,3 +653,64 @@ tevent:
               insinto /usr/include
               doins tevent_internal.h
             }
+
+syslibs_github:
+  generator: builtin-github
+  defaults:
+    category: sys-libs
+    files_dir: "{{ .Values.pn }}"
+    template: ../../templates/simple-github.tmpl
+
+  packages:
+    - liburing:
+        github:
+          user: axboe
+        transform:
+          - kind: string
+            match: 'liburing '
+            replace: ''
+          - kind: string
+            match: 'liburing-'
+            replace: ''
+          - kind: string
+            match: 'Liburing '
+            replace: ''
+        vars:
+          inherit:
+            - autotools
+            - toolchain-funcs
+          iuse: examples static-libs
+          bdepend: |
+            sys-kernel/linux-headers
+          body: |
+            src_prepare() {
+              default
+              if ! use examples; then
+                sed -e '/examples/d' Makefile -i || die
+              fi
+              sed -e '/test/d' Makefile -i || die
+            }
+            src_configure() {
+              local myconf=(
+                --prefix="${EPREFIX}/usr"
+                --libdir="${EPREFIX}/usr/$(get_libdir)"
+                --libdevdir="${EPREFIX}/usr/$(get_libdir)"
+                --mandir="${EPREFIX}/usr/share/man"
+                --cc="$(tc-getCC)"
+                --cxx="$(tc-getCXX)"
+                --use-libc
+              )
+              # No autotools configure! "econf" will fail.
+              TMPDIR="${T}" ./configure "${myconf[@]}" || die
+            }
+            src_compile() {
+              emake V=1 AR="$(tc-getAR)" RANLIB="$(tc-getRANLIB)"
+            }
+            src_install() {
+              default
+              einstalldocs
+              if ! use static-libs ; then
+                find "${ED}" -type f -name "*.a" -delete || die
+              fi
+            }
+
