[media-kit] Autogen media-gfx/inkscape
Needs mark-devkit-0.21.1

diff --git a/media-kit/autogen.kit.d/base.yml b/media-kit/autogen.kit.d/base.yml
--- a/media-kit/autogen.kit.d/base.yml
+++ b/media-kit/autogen.kit.d/base.yml
@@ -768,6 +768,176 @@ sdl_image_autogen:
           - '<4.0'
 
 
+inkscape:
+  generator: builtin-dirlisting
+  template:
+    engine: helm
+
+  defaults:
+    files_dir: "{{ .Values.pn }}"
+    template: ../../templates/simple.tmpl
+    category: media-gfx
+    dir:
+      url: https://inkscape.org/release/all/source/archive
+      matcher: 'inkscape-.*.tar.xz$'
+      exclude: "beta|rc"
+    transform:
+      - kind: string
+        match: "inkscape-"
+        replace: ""
+      - kind: string
+        match: ".tar.xz"
+        replace: ""
+    vars:
+      homepage: https://inkscape.org/ https://gitlab.com/inkscape/inkscape/
+      desc: SVG based generic vector-drawing program
+      python_compat: python3+
+      inherit:
+        - cmake
+        - flag-o-matic
+        - xdg
+        - toolchain-funcs
+        - python-single-r1
+      license: GPL-2 LGPL-2.1
+      iuse: |
+        cdr dia exif graphicsmagick imagemagick inkjar jemalloc jpeg nls
+        openmp postscript readline spell svg2 visio wpg X
+      required_use: '${PYTHON_REQUIRED_USE}'
+      bdepend: |
+        dev-util/glib-utils
+        dev-util/intltool
+        sys-devel/gettext
+        virtual/pkgconfig
+      cdepend: |
+        ${PYTHON_DEPS}
+        app-text/poppler[cairo]
+        dev-cpp/cairomm:0
+        dev-cpp/glibmm
+        dev-cpp/gtkmm:3.0
+        dev-cpp/pangomm
+        dev-libs/boehm-gc
+        dev-libs/boost:=[stacktrace]
+        dev-libs/double-conversion:=
+        dev-libs/glib
+        dev-libs/libsigc++:2
+        dev-libs/libxml2
+        dev-libs/libxslt
+        dev-libs/gdl:3
+        dev-libs/popt
+        media-gfx/potrace
+        media-libs/fontconfig
+        media-libs/freetype:2
+        media-libs/lcms:2
+        media-libs/libpng:0=
+        net-libs/libsoup:2.4
+        sci-libs/gsl:=
+        x11-libs/pango
+        x11-libs/gtk+:3[X?]
+        X? ( x11-libs/libX11 )
+        $(python_gen_cond_dep '
+          dev-python/appdirs[${PYTHON_USEDEP}]
+          dev-python/cachecontrol[${PYTHON_USEDEP}]
+          dev-python/cssselect[${PYTHON_USEDEP}]
+          dev-python/filelock[${PYTHON_USEDEP}]
+          dev-python/lxml[${PYTHON_USEDEP}]
+          dev-python/pygobject[${PYTHON_USEDEP}]
+          media-gfx/scour[${PYTHON_USEDEP}]
+        ')
+        cdr? (
+          app-text/libwpg:0.3
+          dev-libs/librevenge
+          media-libs/libcdr
+        )
+        exif? ( media-libs/libexif )
+        imagemagick? (
+          !graphicsmagick? ( media-gfx/imagemagick:=[cxx] )
+          graphicsmagick? ( media-gfx/graphicsmagick:=[cxx] )
+        )
+        jemalloc? ( dev-libs/jemalloc )
+        jpeg? ( media-libs/libjpeg-turbo:= )
+        readline? ( sys-libs/readline:= )
+        spell? ( app-text/gspell )
+        visio? (
+          app-text/libwpg
+          dev-libs/librevenge
+          media-libs/libvisio
+        )
+        wpg? (
+          app-text/libwpg
+          dev-libs/librevenge
+        )
+      rdepend: |
+        ${CDEPEND}
+        $(python_gen_cond_dep '
+          dev-python/numpy[${PYTHON_USEDEP}]
+        ')
+        dia? ( app-office/dia )
+        postscript? ( app-text/ghostscript-gpl )
+      depend: '${CDEPEND}'
+
+      body: |
+        pkg_pretend() {
+          use openmp && tc-check-openmp
+        }
+        pkg_setup() {
+          use openmp && tc-check-openmp
+          python-single-r1_pkg_setup
+        }
+
+        src_unpack() {
+          default
+          [[ -d "${S}" ]] || mv -v "${WORKDIR}/${P}_202"?-??-* "${S}" || die
+        }
+
+        src_prepare() {
+          cmake_src_prepare
+          sed -i "/install.*COPYING/d" CMakeScripts/ConfigCPack.cmake || die
+        }
+        src_configure() {
+          # aliasing unsafe wrt #310393
+          append-flags -fno-strict-aliasing
+          local mycmakeargs=(
+            # -DWITH_LPETOOL   # Compile with LPE Tool and experimental LPEs enabled
+            -DWITH_NLS=ON
+            -DENABLE_POPPLER=ON
+            -DENABLE_POPPLER_CAIRO=ON
+            -DWITH_PROFILING=OFF
+            -DWITH_INTERNAL_2GEOM=ON
+            -DBUILD_TESTING=OFF
+            -DWITH_LIBCDR=$(usex cdr)
+            -DWITH_IMAGE_MAGICK=$(usex imagemagick $(usex !graphicsmagick)) # requires ImageMagick 6, only IM must be enabled
+            -DWITH_GRAPHICS_MAGICK=$(usex graphicsmagick $(usex imagemagick)) # both must be enabled to use GraphicsMagick
+            -DWITH_GNU_READLINE=$(usex readline)
+            -DWITH_GSPELL=$(usex spell)
+            -DWITH_JEMALLOC=$(usex jemalloc)
+            -DENABLE_LCMS=ON
+            -DWITH_OPENMP=$(usex openmp)
+            -DBUILD_SHARED_LIBS=ON
+            -DWITH_SVG2=$(usex svg2)
+            -DWITH_LIBVISIO=$(usex visio)
+            -DWITH_LIBWPG=$(usex wpg)
+            -DWITH_X11=$(usex X)
+            -DWITH_NLS=$(usex nls)
+          )
+          cmake_src_configure
+        }
+        src_install() {
+          cmake_src_install
+          find "${ED}" -type f -name "*.la" -delete || die
+          find "${ED}"/usr/share/man -type f -maxdepth 3 -name '*.bz2' -exec bzip2 -d {} \; || die
+          find "${ED}"/usr/share/man -type f -maxdepth 3 -name '*.gz' -exec gzip -d {} \; || die
+          local extdir="${ED}"/usr/share/${PN}/extensions
+          if [[ -e "${extdir}" ]] && [[ -n $(find "${extdir}" -mindepth 1) ]]; then
+            python_optimize "${ED}"/usr/share/${PN}/extensions
+          fi
+          # Empty directory causes sandbox issues, see Gentoo bug #761915
+          rm -r "${ED}/usr/share/inkscape/fonts" || die "Failed to remove fonts directory."
+        }
+
+  packages:
+    - inkscape:
+
+
 blender:
   generator: builtin-dirlisting
   template:
