[llvm-kit] Autogen clang,libcxx,clang-*
* autogen sys-devel/clang:16
* autogen sys-devel/clang-common:16
* autogen sys-devel/clang-runtime:16
* autogen sys-libs/libcxx
* autogen sys-libs/libcxxabi
* autogen sys-libs/libomp

Bugs: macaroni-os/mark-issues#86

diff --git a/llvm-kit/autogen.kit.d/base.yml b/llvm-kit/autogen.kit.d/base.yml
--- a/llvm-kit/autogen.kit.d/base.yml
+++ b/llvm-kit/autogen.kit.d/base.yml
@@ -1,9 +1,10 @@
-sys_devel_llvm:
+sys_devel_llvm16:
   generator: builtin-github
 
   defaults:
     files_dir: "{{ .Values.pn }}"
     category: sys-devel
+    template: ../../templates/simple.tmpl
     vars:
       homepage: https://llvm.org/
       license: Apache-2.0-with-LLVM-exceptions UoI-NCSA BSD public-domain rc
@@ -154,7 +155,7 @@ sys_devel_llvm:
       per_page: 1000
       #per_page: 300
     assets:
-      - name: "{{ .Values.pn }}-{{ .Values.version }}.src.tar.xz"
+      - name: "llvm-project-{{ .Values.version }}.src.tar.xz"
         matcher: "llvm-project-.*.src.tar.xz"
     transform:
       - kind: string
@@ -164,7 +165,153 @@ sys_devel_llvm:
       - '<17.0'
 
   packages:
+
+    - clang:
+        template: templates/clang.tmpl
+        vars:
+          clang_components:
+            # common stuff
+            - bash-autocomplete
+            - clang-cmake-exports
+            - clang-headers
+            - clang-resource-headers
+            - libclang-headers
+            - libclang-python-bindings
+
+            - aarch64-resource-headers
+            - arm-common-resource-headers
+            - arm-resource-headers
+            - core-resource-headers
+            - cuda-resource-headers
+            - hexagon-resource-headers
+            - hip-resource-headers
+            - hlsl-resource-headers
+            - mips-resource-headers
+            - opencl-resource-headers
+            - openmp-resource-headers
+            - ppc-htm-resource-headers
+            - ppc-resource-headers
+            - riscv-resource-headers
+            - systemz-resource-headers
+            - utility-resource-headers
+            - ve-resource-headers
+            - webassembly-resource-headers
+            - windows-resource-headers
+            - x86-resource-headers
+
+            - # libs
+            - clang-cpp
+            - libclang
+
+            - # tools
+            - amdgpu-arch
+            - c-index-test
+            - clang
+            - clang-format
+            - clang-offload-bundler
+            - clang-offload-packager
+            - clang-refactor
+            - clang-repl
+            - clang-rename
+            - clang-scan-deps
+            - diagtool
+            - hmaptool
+            - nvptx-arch
+
+            - # needed for cross-compiling Clang
+            - clang-tblgen
+          clang_components_extra:
+            # extra tools
+            - clang-apply-replacements
+            - clang-change-namespace
+            - clang-doc
+            - clang-include-cleaner
+            - clang-include-fixer
+            - clang-move
+            - clang-pseudo
+            - clang-query
+            - clang-reorder-fields
+            - clang-tidy
+            - clang-tidy-headers
+            - clangd
+            - find-all-symbols
+            - modularize
+            - pp-trace
+          clang_components_static_analyzer:
+            - clang-check
+            - clang-extdef-mapping
+            - scan-build
+            - scan-build-py
+            - scan-view
+          inherit:
+            - cmake
+            - flag-o-matic
+            - python-single-r1
+            - toolchain-funcs
+          slot: 16
+          python_compat: "python3+"
+          desc: C language family frontend for LLVM
+          license: Apache-2.0-with-LLVM-exceptions UoI-NCSA MIT
+          iuse: |
+            debug +extra ieee-long-double +pie +static-analyzer xml llvm-libunwind
+            default-compiler-rt default-libcxx default-lld
+          required_use: "${PYTHON_REQUIRED_USE}"
+          depend: |
+            ~sys-devel/llvm-{{ .Values.version }}:{{ .Values.slot }}[debug=]
+            static-analyzer? ( dev-lang/perl:* )
+            xml? ( dev-libs/libxml2:2 )
+          rdepend: |
+            ${PYTHON_DEPS}
+            ${DEPEND}
+          bdepend: |
+            ${PYTHON_DEPS}
+            dev-util/cmake
+            xml? ( virtual/pkgconfig )
+          pdepend: |
+            sys-devel/clang-common
+            ~sys-devel/clang-runtime-{{ .Values.version }}
+            default-compiler-rt? (
+              =sys-libs/compiler-rt-${PV%_*}*
+              llvm-libunwind? ( sys-libs/llvm-libunwind )
+              !llvm-libunwind? ( sys-libs/libunwind )
+            )
+            default-libcxx? ( >=sys-libs/libcxx-{{ .Values.version }} )
+            default-lld? ( sys-devel/lld )
+
+    - clang-common:
+        vars:
+          slot: 16
+          desc: Common files shared between multiple slots of clang
+          license: Apache-2.0-with-LLVM-exceptions UoI-NCSA BSD public-domain rc
+          s: ${WORKDIR}/clang/utils
+          pdepend: |
+            sys-devel/clang:*
+          inherit:
+            - bash-completion-r1
+          body: |
+            src_install() {
+              newbashcomp bash-autocomplete.sh clang
+            }
+
+    - clang-runtime:
+        ignore_artefacts: true
+        vars:
+          slot: 16
+          desc: Meta-ebuild for clang runtime libraries
+          license: metapackage
+          iuse: +compiler-rt libcxx openmp +sanitize
+          required_use: |
+            sanitize? ( compiler-rt )
+          rdepend: |
+            compiler-rt? (
+              ~sys-libs/compiler-rt-{{ .Values.version }}:${SLOT}
+              sanitize? ( ~sys-libs/compiler-rt-sanitizers-{{ .Values.version }}:${SLOT} )
+            )
+            libcxx? ( >=sys-libs/libcxx-{{ .Values.version }} )
+            openmp? ( >=sys-libs/libomp-{{ .Values.version }} )
+
     - llvm:
+        template: templates/llvm.tmpl
         vars:
           python_compat: "python3+"
           slot: 16
@@ -204,7 +351,6 @@ sys_devel_llvm:
             gold? ( >=sys-devel/llvmgold-${SLOT} )
 
     - llvm-common:
-        template: ../../templates/simple.tmpl
         vars:
           desc: Common files shared between multiple slots of LLVM
           s: "${WORKDIR}/llvm-src/llvm/utils/vim"
@@ -219,3 +365,260 @@ sys_devel_llvm:
               newdoc README README.vim
               dodoc vimrc
             }
+
+    - libcxxabi:
+        category: sys-libs
+        vars:
+          desc: Low level support for a standard C++ library
+          iuse: +libunwind clang static-libs
+          homepage: https://libcxxabi.llvm.org/
+          python_compat: python3+
+          s: "${WORKDIR}/llvm-src/runtimes"
+          extra_envs:
+            - "CMAKE_BUILD_TYPE=RelWithDebInfo"
+          inherit:
+            - cmake
+            - python-any-r1
+            - toolchain-funcs
+          # Enable libunwind fails with: x86_64-pc-linux-gnu/bin/ld: cannot find -lunwind_shared: No such file or directory
+          rdepend: |
+            libunwind? (
+              || (
+                sys-libs/libunwind[static-libs?]
+                sys-libs/llvm-libunwind[static-libs?]
+              )
+            )
+          depend: |
+            ${RDEPEND}
+            sys-devel/llvm:16
+          bdepend: |
+            clang? ( sys-devel/clang:16 )
+          body: |
+            post_src_unpack() {
+              mv {{ .Values.github_repo }}-* llvm-src
+            }
+            src_configure() {
+              local S=${S}/libcxxabi
+              if use clang; then
+                local -x CC=clang
+                local -x CXX=clang++
+              fi
+              # link against compiler-rt instead of libgcc if we are using clang with libunwind
+              local want_compiler_rt=OFF
+              if use libunwind && tc-is-clang; then
+                  local compiler_rt=$($(tc-getCC) ${CFLAGS} ${CPPFLAGS} \
+                      ${LDFLAGS} -print-libgcc-file-name)
+                  if [[ ${compiler_rt} == *libclang_rt* ]]; then
+                      want_compiler_rt=ON
+                  fi
+              fi
+              local libdir=$(get_libdir)
+              local mycmakeargs=(
+                -DPython3_EXECUTABLE="${PYTHON}"
+                -DLLVM_ENABLE_RUNTIMES="libunwind;libcxxabi;libcxx"
+                -DLLVM_ENABLE_EH=ON
+                -DLLVM_ENABLE_RTTI=ON
+                -DLLVM_INCLUDE_TESTS=OFF
+                -DLLVM_LIBDIR_SUFFIX=${libdir#lib}
+                -DLIBCXXABI_LIBDIR_SUFFIX=${libdir#lib}
+                -DLIBCXXABI_ENABLE_SHARED=ON
+                -DLIBCXXABI_USE_LLVM_UNWINDER=$(usex libunwind)
+                -DLIBCXXABI_ENABLE_STATIC=$(usex static-libs)
+                -DLIBCXXABI_INCLUDE_TESTS=OFF
+                -DLIBCXXABI_USE_COMPILER_RT=${want_compiler_rt}
+                # upstream is omitting standard search path for this
+                # probably because gcc & clang are bundling their own unwind.h
+                -DLIBCXXABI_LIBUNWIND_INCLUDES="${EPREFIX}"/usr/include
+                -DLIBCXXABI_ADDITIONAL_LIBRARIES="-Wl,-lunwind"
+                -DLIBCXX_LIBDIR_SUFFIX=
+                -DLIBCXX_ENABLE_SHARED=ON
+                -DLIBCXX_ENABLE_STATIC=OFF
+                -DLIBCXX_CXX_ABI=libcxxabi
+                -DLIBCXX_ENABLE_ABI_LINKER_SCRIPT=OFF
+                -DLIBCXX_HAS_MUSL_LIBC=$(usex elibc_musl)
+                -DLIBCXX_HAS_GCC_S_LIB=OFF
+                -DLIBCXX_INCLUDE_BENCHMARKS=OFF
+                -DLIBCXX_INCLUDE_TESTS=OFF
+              )
+              cmake_src_configure
+            }
+            src_compile() {
+              cmake_build cxxabi
+            }
+            src_install() {
+              DESTDIR="${D}" cmake_build install-cxxabi
+            }
+
+
+    - libcxx:
+        category: sys-libs
+        vars:
+          desc: New implementation of the C++ standard library, targeting C++11
+          iuse: static-libs clang +libcxxabi +libunwind
+          homepage: https://libcxx.llvm.org/
+          python_compat: python3+
+          s: "${WORKDIR}/llvm-src/runtimes"
+          inherit:
+            - cmake
+            - python-any-r1
+            - toolchain-funcs
+          required_use: libunwind? ( libcxxabi )
+          rdepend: |
+            libcxxabi? ( ~sys-libs/libcxxabi-${PV}[static-libs?] )
+            !libcxxabi? ( sys-devel/gcc[cxx] )
+          depend: |
+            ${RDEPEND}
+            sys-devel/llvm:16
+          bdepend: |
+            clang? ( sys-devel/clang:16 )
+          body: |
+            post_src_unpack() {
+              mv {{ .Values.github_repo }}-* llvm-src
+            }
+            src_configure() {
+              local S=${S}/libcxx
+              if use clang; then
+                local -x CC=clang
+                local -x CXX=clang++
+              fi
+              local cxxabi cxxabi_incs
+              if use libcxxabi; then
+                cxxabi=system-libcxxabi
+                cxxabi_incs="${EPREFIX}/usr/include/c++/v1"
+              else
+                local gcc_inc="${EPREFIX}/usr/lib/gcc/${CHOST}/$(gcc-fullversion)/include/g++-v$(gcc-major-version)"
+                cxxabi=libsupc++
+                cxxabi_incs="${gcc_inc};${gcc_inc}/${CHOST}"
+              fi
+
+              # link against compiler-rt instead of libgcc if we are using clang with libunwind
+              local want_compiler_rt=OFF
+              if use libunwind && tc-is-clang; then
+                  local compiler_rt=$($(tc-getCC) ${CFLAGS} ${CPPFLAGS} \
+                      ${LDFLAGS} -print-libgcc-file-name)
+                  if [[ ${compiler_rt} == *libclang_rt* ]]; then
+                      want_compiler_rt=ON
+                  fi
+              fi
+              local libdir=$(get_libdir)
+              local mycmakeargs=(
+                -DPython3_EXECUTABLE="${PYTHON}"
+                -DLLVM_ENABLE_RUNTIMES=libcxx
+                -DLLVM_INCLUDE_TESTS=OFF
+                -DLIBCXX_USE_LLVM_UNWINDER=$(usex libunwind)
+                -DLIBCXX_LIBDIR_SUFFIX=${libdir#lib}
+                -DLIBCXX_ENABLE_SHARED=ON
+                -DLIBCXX_ENABLE_STATIC=$(usex static-libs)
+                -DLIBCXX_CXX_ABI=${cxxabi}
+                -DLIBCXX_CXX_ABI_INCLUDE_PATHS=${cxxabi_incs}
+                -DLIBCXX_ENABLE_ABI_LINKER_SCRIPT=OFF
+                -DLIBCXX_HAS_MUSL_LIBC=$(usex elibc_musl)
+                -DLIBCXX_INCLUDE_BENCHMARKS=OFF
+                -DLIBCXX_HAS_GCC_S_LIB=OFF
+                -DLIBCXX_INCLUDE_TESTS=OFF
+                -DLIBCXX_ADDITIONAL_LIBRARIES="-Wl,-lunwind,-lgcc"
+                -DLIBCXX_USE_COMPILER_RT=${want_compiler_rt}
+              )
+              cmake_src_configure
+            }
+            # Usage: deps
+            gen_ldscript() {
+              local output_format
+              output_format=$($(tc-getCC) ${CFLAGS} ${LDFLAGS} -Wl,--verbose 2>&1 | sed -n 's/^OUTPUT_FORMAT("\([^"]*\)",.*/\1/p')
+              [[ -n ${output_format} ]] && output_format="OUTPUT_FORMAT ( ${output_format} )"
+
+              cat <<-END_LDSCRIPT
+            /* GNU ld script
+               Include missing dependencies
+            */
+            ${output_format}
+            GROUP ( $@ )
+            END_LDSCRIPT
+            }
+            gen_static_ldscript() {
+              local libdir=$(get_libdir)
+              local cxxabi_lib=$(usex libcxxabi "libc++abi.a" "libsupc++.a")
+              # Generate libc++.a ldscript for inclusion of its dependencies so that
+              # clang++ -stdlib=libc++ -static works out of the box.
+              local deps="libc++_static.a ${cxxabi_lib} $(usex libunwind libunwind.a libgcc_eh.a)"
+              # On Linux/glibc it does not link without libpthread or libdl. It is
+              # fine on FreeBSD.
+              use elibc_glibc && deps+=" libpthread.a libdl.a"
+              gen_ldscript "${deps}" > "${ED}/usr/${libdir}/libc++.a" || die
+            }
+            gen_shared_ldscript() {
+              local libdir=$(get_libdir)
+              # libsupc++ doesn't have a shared version
+              local cxxabi_lib=$(usex libcxxabi "libc++abi.so" "libsupc++.a")
+              mv "${ED}/usr/${libdir}/libc++.so" "${ED}/usr/${libdir}/libc++_shared.so" || die
+              local deps="libc++_shared.so ${cxxabi_lib} $(usex libunwind libunwind.so libgcc_s.so)"
+              gen_ldscript "${deps}" > "${ED}/usr/${libdir}/libc++.so" || die
+            }
+            src_install() {
+              cmake_src_install
+              mv "${ED}/usr/${libdir}/libc++experimental.a" "${ED}/usr/${libdir}/libc++_static.a" || die
+              gen_shared_ldscript
+              if use static-libs ; then
+                gen_static_ldscript
+              fi
+            }
+
+    - libomp:
+        category: sys-libs
+        vars:
+          desc: OpenMP runtime library for LLVM/clang compiler
+          iuse: cuda debug hwloc offload ompt llvm_targets_AMDGPU llvm_targets_NVPTX abi_x86_64
+          homepage: https://openmp.llvm.org/
+          license: Apache-2.0-with-LLVM-exceptions || ( UoI-NCSA MIT )
+          s: "${WORKDIR}/llvm-src/openmp"
+          inherit:
+            - cmake
+          required_use: |
+            cuda? ( llvm_targets_NVPTX )
+            offload? ( cuda? ( abi_x86_64 ) )
+          rdepend: |
+            hwloc? ( sys-apps/hwloc:0= )
+            offload? (
+              virtual/libelf
+              dev-libs/libffi
+              ~sys-devel/llvm-{{ .Values.version }}
+            )
+          depend: |
+            ${RDEPEND}
+          bdepend: |
+            dev-lang/perl
+            offload? (
+              llvm_targets_AMDGPU? ( sys-devel/clang )
+              llvm_targets_NVPTX? ( sys-devel/clang )
+              virtual/pkgconfig
+            )
+          body: |
+            post_src_unpack() {
+              mv {{ .Values.github_repo }}-* llvm-src
+            }
+            src_configure() {
+              # LLVM_ENABLE_ASSERTIONS=NO does not guarantee this for us, #614844
+              use debug || local -x CPPFLAGS="${CPPFLAGS} -DNDEBUG"
+              local libdir="$(get_libdir)"
+              local mycmakeargs=(
+                -DOPENMP_LIBDIR_SUFFIX="${libdir#lib}"
+                -DLIBOMP_USE_HWLOC=$(usex hwloc)
+                -DLIBOMP_OMPT_SUPPORT=$(usex ompt)
+                -DOPENMP_ENABLE_LIBOMPTARGET=$(usex offload)
+                # do not install libgomp.so & libiomp5.so aliases
+                -DLIBOMP_INSTALL_ALIASES=OFF
+                # disable unnecessary hack copying stuff back to srcdir
+                -DLIBOMP_COPY_EXPORTS=OFF
+                # prevent trying to access the GPU
+                -DLIBOMPTARGET_AMDGPU_ARCH=LIBOMPTARGET_AMDGPU_ARCH-NOTFOUND
+                -DOPENMP_LLVM_LIT_EXECUTABLE="${EPREFIX}/usr/bin/lit"
+              )
+              use offload && mycmakeargs+=(
+                -DLIBOMPTARGET_BUILD_AMDGPU_PLUGIN=$(usex llvm_targets_AMDGPU)
+                -DLIBOMPTARGET_BUILD_CUDA_PLUGIN=$(usex llvm_targets_NVPTX)
+              )
+              addpredict /dev/nvidiactl
+              cmake_src_configure
+            }
+
+
