[desktop-kit] Autogen sddm

diff --git a/desktop-kit/autogen.kit.d/base.yml b/desktop-kit/autogen.kit.d/base.yml
--- a/desktop-kit/autogen.kit.d/base.yml
+++ b/desktop-kit/autogen.kit.d/base.yml
@@ -646,6 +646,114 @@ general_github:
       query: releases
 
   packages:
+
+    - sddm:
+        vars:
+          extra_envs:
+            - 'PLOCALES="ar bn ca cs da de es et eu fi fr he hi_IN hu ie is it ja kk ko lt lv nb nl nn oc pl pt_BR pt_PT ro ru sk sr sr@ijekavian sr@ijekavianlatin sr@latin sv tr uk zh_CN zh_TW"'
+          inherit:
+            - cmake-utils
+            - l10n
+            - systemd
+            - user
+          patches:
+            - sddm-0.20.0-respect-user-flags.patch
+            - sddm-0.21.0_p20251101-fix-restart-greeter.patch
+            - sddm-0.21.0_p20250310-set-XAUTHLOCALHOSTNAME.patch
+            - sddm-0.21.0_p20251101-fix-terminal-clearing.patch
+          iuse: elogind +pam systemd qt5
+          required_use: |
+            ?? ( elogind systemd )
+          cdepend: |
+            qt5? (
+              dev-qt/qtcore:5
+              dev-qt/qtdbus:5
+              dev-qt/qtdeclarative:5
+              dev-qt/qtgui:5
+              dev-qt/qtnetwork:5
+            )
+            !qt5? (
+              dev-qt/qtbase:6[gui]
+              dev-qt/qtdeclarative:6
+            )
+            sys-libs/pam
+            x11-libs/libXau
+            x11-libs/libxcb:=
+            elogind? (
+              sys-auth/elogind
+            )
+            pam? ( sys-libs/pam )
+            systemd? ( sys-apps/systemd:= )
+            !systemd? ( sys-power/upower )
+          rdepend: |
+            ${CDEPEND}
+            x11-misc/xcb
+          depend: |
+            ${CDEPEND}
+            dev-python/docutils
+            kde-frameworks/extra-cmake-modules
+            qt5? (
+              dev-qt/linguist-tools:5
+            )
+          bdepend: |
+            virtual/pkgconfig
+          body: |
+            src_prepare() {
+              cmake-utils_src_prepare
+              disable_locale() {
+                sed -e "/${1}\.ts/d" -i data/translations/CMakeLists.txt || die
+              }
+              l10n_find_plocales_changes "data/translations" "" ".ts"
+              l10n_for_each_disabled_locale_do disable_locale
+              sed -e "/^find_package/s/ Test//" -i CMakeLists.txt || die
+              cmake_comment_add_subdirectory test
+            }
+            src_configure() {
+              local mycmakeargs=(
+                -DENABLE_PAM=$(usex pam)
+                -DNO_SYSTEMD=$(usex '!systemd')
+                -DUSE_ELOGIND=$(usex 'elogind')
+                -DBUILD_MAN_PAGES=ON
+                -DDBUS_CONFIG_FILENAME="org.freedesktop.sddm.conf"
+              )
+              if ! use qt5 ; then
+                mycmakeargs+=(
+                  -DBUILD_WITH_QT6=ON
+                )
+              fi
+              cmake-utils_src_configure
+            }
+            src_install() {
+              cmake-utils_src_install
+              if ! use systemd; then
+                insinto /etc/logrotate.d
+                newins "${FILESDIR}/sddm.logrotate" sddm
+              fi
+              # Create a default.conf as upstream dropped /etc/sddm.conf w/o replacement
+              local confd="/usr/share/sddm/sddm.conf.d"
+              dodir ${confd}
+              "${D}"/usr/bin/sddm --example-config > "${D}/${confd}"/00default.conf \
+                || die "Failed to create 00default.conf"
+              sed -e "/^InputMethod/s/qtvirtualkeyboard//" \
+                -i "${D}/${confd}"/00default.conf || die
+              if ! use elogind && ! use systemd ; then
+                # When both elogind and systemd are disable the configure.ac
+                # generates the file /etc/pam.d/sddm-greeter with pam_systemd.so
+                # intergration. This generates errors on logs.
+                sed -i -e '/pam_systemd.so/d' "${D}"/etc/pam.d/sddm-greeter
+              fi
+            }
+            pkg_postinst() {
+              elog "Starting with 0.18.0, SDDM no longer installs /etc/sddm.conf"
+              elog "Use it to override specific options. SDDM defaults are now"
+              elog "found in: /usr/share/sddm/sddm.conf.d/00default.conf"
+              enewgroup ${PN}
+              enewuser ${PN} -1 -1 /var/lib/${PN} ${PN},video
+              if use systemd ; then
+                systemd_reenable sddm.service
+              fi
+            }
+
     - xdg-desktop-portal:
         template: ../../templates/simple.tmpl
         github:
