[core-kit] autogen coreutils
Closes: macaroni-os/mark-issues#562

diff --git a/core-kit/autogen.kit.d/core.yml b/core-kit/autogen.kit.d/core.yml
--- a/core-kit/autogen.kit.d/core.yml
+++ b/core-kit/autogen.kit.d/core.yml
@@ -121,6 +121,307 @@ core_dirlisting:
     category: sys-apps
 
   packages:
+
+    - coreutils:
+        dir:
+          url: 'https://gnuftp.mirror.garr.it/{{ .Values.pn }}/'
+          matcher: "{{ .Values.pn }}-.*.tar.xz$"
+        transform:
+          - kind: string
+            match: '{{ .Values.pn }}-'
+            replace: ''
+          - kind: string
+            match: '.tar.xz'
+            replace: ''
+        assets:
+          - name: "{{ .Values.pn }}-{{ .Values.version }}.tar.xz"
+        vars:
+          lib_depend:
+            - use: 'acl'
+              dep:
+                - sys-apps/acl
+              dep_use:
+                - static-libs
+            - use: 'caps'
+              dep:
+                - sys-libs/libcap
+              dep_use:
+                - static-libs
+            - use: 'gmp'
+              dep:
+                - dev-libs/gmp:=
+              dep_use:
+                - static-libs
+            - use: 'xattr'
+              dep:
+                - sys-apps/attr
+              dep_use:
+                - static-libs
+            - use: 'openssl'
+              dep:
+                - dev-libs/openssl:=
+              dep_use:
+                - static-libs
+          rdepend: |
+            !static? (
+              {{- range $p := .Values.lib_depend }}
+                {{- if $p.use | default false }}
+              {{ $p.use }}? (
+                  {{- range $d := $p.dep }}
+                  {{- if $p.dep_use | default false }}
+                    {{- $uses := "" }}
+                    {{- $i := 0 }}
+                    {{- range $u := $p.dep_use }}
+                      {{- if ( not ( eq $u "static-libs" ) ) }}
+                        {{- $i = add1 $i }}
+                        {{- if ( eq $i 1 ) }}
+                          {{- $uses = $u }}
+                        {{- else }}
+                          {{- $uses = list $uses $u | join "," }}
+                        {{- end }}
+                      {{- end }}
+                    {{- end }}
+                    {{- if eq $uses "" }}
+                  {{ $d }}
+                    {{- else }}
+                  {{ $d }}[{{ $uses }}]
+                    {{- end }}
+                  {{- else }}
+                  {{ $d }}
+                  {{- end }}
+                  {{- end }}
+              )
+                {{- else }}
+                  {{- range $d := $p.dep }}
+                  {{- if $p.dep_use | default false }}
+                    {{- $uses := "" }}
+                    {{- $i := 0 }}
+                    {{- range $u := $p.dep_use }}
+                      {{- if ( not ( eq $u "static-libs" ) ) }}
+                        {{- $i = add1 $i }}
+                        {{- if ( eq $i 1 ) }}
+                          {{- $uses = $u }}
+                        {{- else }}
+                          {{- $uses = list $uses $u | join "," }}
+                        {{- end }}
+                      {{- end }}
+                    {{- end }}
+                    {{- if eq $uses "" }}
+              {{ $d }}
+                    {{- else }}
+              {{ $d }}[{{ $uses }}]
+                    {{- end }}
+                  {{- else }}
+              {{ $d }}
+                  {{- end }}
+                  {{- end }}
+                {{- end }}
+              {{- end }}
+            )
+            nls? ( virtual/libintl )
+            hostname? ( !sys-apps/net-tools[hostname] )
+            kill? (
+              !sys-apps/util-linux[kill]
+              !sys-process/procps[kill]
+            )
+            !<sys-apps/shadow-4.17.3
+          depend: |
+            !static? (
+              {{- range $p := .Values.lib_depend }}
+                {{- if $p.use | default false }}
+              {{ $p.use }}? (
+                  {{- range $d := $p.dep }}
+                  {{- if $p.dep_use | default false }}
+                    {{- $uses := "" }}
+                    {{- $i := 0 }}
+                    {{- range $u := $p.dep_use }}
+                      {{- if ( not ( eq $u "static-libs" ) ) }}
+                        {{- $i = add1 $i }}
+                        {{- if ( eq $i 1 ) }}
+                          {{- $uses = $u }}
+                        {{- else }}
+                          {{- $uses = list $uses $u | join "," }}
+                        {{- end }}
+                      {{- end }}
+                    {{- end }}
+                    {{- if eq $uses "" }}
+                  {{ $d }}
+                    {{- else }}
+                  {{ $d }}[{{ $uses }}]
+                    {{- end }}
+                  {{- else }}
+                  {{ $d }}
+                  {{- end }}
+                  {{- end }}
+              )
+                {{- else }}
+                  {{- range $d := $p.dep }}
+                  {{- if $p.dep_use | default false }}
+                    {{- $uses := "" }}
+                    {{- $i := 0 }}
+                    {{- range $u := $p.dep_use }}
+                      {{- if ( not ( eq $u "static-libs" ) ) }}
+                        {{- $i = add1 $i }}
+                        {{- if ( eq $i 1 ) }}
+                          {{- $uses = $u }}
+                        {{- else }}
+                          {{- $uses = list $uses $u | join "," }}
+                        {{- end }}
+                      {{- end }}
+                    {{- end }}
+                    {{- if eq $uses "" }}
+              {{ $d }}
+                    {{- else }}
+              {{ $d }}[{{ $uses }}]
+                    {{- end }}
+                  {{- else }}
+              {{ $d }}
+                  {{- end }}
+                  {{- end }}
+                {{- end }}
+              {{- end }}
+            )
+            static? (
+              {{- range $p := .Values.lib_depend }}
+                {{- if $p.use | default false }}
+              {{ $p.use }}? (
+                  {{- range $d := $p.dep }}
+                  {{- if $p.dep_use | default false }}
+                    {{- $uses := "" }}
+                    {{- $i := 0 }}
+                    {{- range $u := $p.dep_use }}
+                      {{- $i = add1 $i }}
+                      {{- if ( eq $i 1 ) }}
+                        {{- $uses = $u }}
+                      {{- else }}
+                        {{- $uses = list $uses $u | join "," }}
+                      {{- end }}
+                    {{- end }}
+                    {{- if eq $uses "" }}
+                  {{ $d }}
+                    {{- else }}
+                  {{ $d }}[{{ $uses }}]
+                    {{- end }}
+                  {{- else }}
+                  {{ $d }}
+                  {{- end }}
+                  {{- end }}
+              )
+                {{- else }}
+                  {{- range $d := $p.dep }}
+                  {{- if $p.dep_use | default false }}
+                    {{- $uses := "" }}
+                    {{- $i := 0 }}
+                    {{- range $u := $p.dep_use }}
+                      {{- $i = add1 $i }}
+                      {{- if ( eq $i 1 ) }}
+                        {{- $uses = $u }}
+                      {{- else }}
+                        {{- $uses = list $uses $u | join "," }}
+                      {{- end }}
+                    {{- end }}
+                    {{- if eq $uses "" }}
+              {{ $d }}
+                    {{- else }}
+              {{ $d }}[{{ $uses }}]
+                    {{- end }}
+                  {{- else }}
+              {{ $d }}
+                  {{- end }}
+                  {{- end }}
+                {{- end }}
+              {{- end }}
+            )
+          bdepend: |
+            app-arch/xz-utils
+            dev-lang/perl
+          inherit:
+            - flag-o-matic
+            - toolchain-funcs
+          license: GPL-3
+          homepage: https://www.gnu.org/software/coreutils/
+          desc: Standard GNU utilities (chmod, cp, dd, ls, sort, tr, head, wc, who,...)
+          iuse: acl caps gmp hostname kill multicall nls +openssl +split-usr static xattr
+          body: |
+            src_prepare() {
+              default
+              set -- man/*.x
+              touch ${@/%x/1} || die
+              # Avoid perl dep for compiled in dircolors default (bug #348642)
+              if ! has_version dev-lang/perl ; then
+                touch src/dircolors.h || die
+                touch ${@/%x/1} || die
+              fi
+            }
+            src_configure() {
+              local myconf=(
+                --with-packager="MacaroniOS"
+                --with-packager-version="{{ .Values.version }}"
+                --with-packager-bug-reports="https://github.com/macaroni-os/mark-issues"
+                # kill/uptime - procps
+                # su          - shadow
+                # hostname    - net-tools
+                --enable-install-program="arch,$(usev hostname),$(usev kill)"
+                --enable-no-install-program="$(usev !hostname),$(usev !kill),su,uptime"
+                --enable-largefile
+                $(usex caps '' --disable-libcap)
+                $(use_enable nls)
+                $(use_enable acl)
+                $(use_enable multicall single-binary)
+                $(use_enable xattr)
+                $(use_with gmp libgmp)
+                $(use_with openssl)
+              )
+
+              if use gmp ; then
+                myconf+=( --with-libgmp-prefix="${ESYSROOT}"/usr )
+              fi
+
+              export gl_cv_func_mknod_works=yes
+
+              if use static ; then
+                append-ldflags -static
+                # bug #321821
+                sed -i '/elf_sys=yes/s:yes:no:' configure || die
+              fi
+
+              export ac_cv_{header_selinux_{context,flash,selinux}_h,search_setfilecon}=no
+              econf "${myconf[@]}"
+            }
+            src_install() {
+              default
+              insinto /etc
+              newins src/dircolors.hin DIR_COLORS
+              if use split-usr ; then
+                cd "${ED}"/usr/bin || die
+                dodir /bin
+                # Move critical binaries into /bin (required by FHS)
+                local fhs="cat chgrp chmod chown cp date dd df echo false ln ls
+                           mkdir mknod mv pwd rm rmdir stty sync true uname"
+                mv ${fhs} ../../bin/ || die "Could not move FHS bins!"
+                if use hostname ; then
+                  mv hostname ../../bin/ || die
+                fi
+                if use kill ; then
+                  mv kill ../../bin/ || die
+                fi
+                # Move critical binaries into /bin (common scripts)
+                # (Why are these required for booting?)
+                local com="basename chroot cut dir dirname du env expr head mkfifo
+                           mktemp readlink seq sleep sort tail touch tr tty vdir wc yes"
+                mv ${com} ../../bin/ || die "Could not move common bins!"
+
+                # Create a symlink for uname in /usr/bin/ since autotools require it.
+                # (Other than uname, we need to figure out why we are
+                # creating symlinks for these in /usr/bin instead of leaving
+                # the files there in the first place...)
+                local x
+                for x in ${com} uname ; do
+                  dosym ../../bin/${x} /usr/bin/${x}
+                done
+              fi
+            }
+
     - mime-types:
         category: app-misc
         dir:
