[xorg-kit] autogen dev-libs, dev-util packages
* autogen dev-libs/glib:2
* autogen dev-libs/gobject-introspection
* autogen dev-libs/gobject-introspection-common
* autogen dev-util/desktop-file-utils
* autogen dev-util/gdbus-codegen
* autogen dev-util/glib-utils
* autogen x11-libs/pango

Closes: macaroni-os/mark-issues#535

diff --git a/xorg-kit/autogen.kit.d/base.yml b/xorg-kit/autogen.kit.d/base.yml
--- a/xorg-kit/autogen.kit.d/base.yml
+++ b/xorg-kit/autogen.kit.d/base.yml
@@ -2331,3 +2331,431 @@ cairo:
               fi
             }
 
+
+gnome_sources:
+  generator: builtin-dirlisting
+  generator_opts:
+    # Limit rate at 1reqs/sec
+    rate_limiter: "1"
+  template:
+    engine: helm
+
+  defaults:
+    files_dir: "{{ .Values.pn }}"
+    template: ../../templates/simple.tmpl
+    dir:
+      url: https://download.gnome.org/sources/{{ .Values.tname | default .Values.pn }}/{{ .Values.release }}/
+      matcher: "{{ .Values.tname | default .Values.pn }}-.*.tar.xz$"
+      exclude: 'rc|alpha|beta'
+    transform:
+      - kind: string
+        match: "{{ .Values.tname | default .Values.pn }}-"
+        replace: ""
+      - kind: string
+        match: ".tar.xz"
+        replace: ""
+    vars:
+      python_compat: python3+
+
+  packages:
+
+    - gdbus-codegen:
+        category: dev-util
+        vars:
+          inherit:
+            - distutils-r1
+          tname: glib
+          release: 2.86
+          rdepend: |
+            ${PYTHON_DEPS}
+          depend: |
+            ${RDEPEND}
+            dev-libs/libxslt
+            app-text/docbook-xsl-stylesheets
+          bdepend: |
+            dev-python/docutils
+          pdepend: |
+            >=dev-libs/glib-{{ .Values.version }}
+          s: "${WORKDIR}/glib-{{ .Values.version }}/gio/gdbus-2.0/codegen"
+          patches:
+            - gdbus-codegen-2.60.3-sitedir.patch
+          body: |
+            src_prepare() {
+              sed -e 's:@PYTHON@:python:' gdbus-codegen.in > gdbus-codegen || die
+              sed -e "s:@VERSION@:${PV}:" \
+                -e "s:@MAJOR_VERSION@:$(ver_cut 1):" \
+                -e "s:@MINOR_VERSION@:$(ver_cut 2):" config.py.in > config.py || die
+              cp "${FILESDIR}/setup.py-2.32.4" setup.py || die "cp failed"
+              sed -e "s/@PV@/${PV}/" -i setup.py || die "sed setup.py failed"
+              distutils-r1_src_prepare
+            }
+            do_xsltproc_command() {
+              # Taken from meson.build for manual manpage building - keep in sync (also copied to dev-util/glib-utils)
+              xsltproc \
+                --nonet \
+                --stringparam man.output.quietly 1 \
+                --stringparam funcsynopsis.style ansi \
+                --stringparam man.th.extra1.suppress 1 \
+                --stringparam man.authors.section.enabled 0 \
+                --stringparam man.copyright.section.enabled 0 \
+                -o "${2}" \
+                http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl \
+                "${1}" || die "manpage generation failed"
+            }
+            src_compile() {
+              distutils-r1_src_compile
+              rst2man \
+                "${WORKDIR}/glib-${PV}/docs/reference/gio/gdbus-codegen.rst" \
+                "${WORKDIR}/glib-${PV}/docs/reference/gio/gdbus-codegen.1"
+            }
+            src_install() {
+              distutils-r1_src_install
+              doman "${WORKDIR}/glib-${PV}/docs/reference/gio/gdbus-codegen.1"
+            }
+
+    - gobject-introspection:
+        category: dev-libs
+        vars:
+          inherit:
+            - meson
+            - python-single-r1
+            - toolchain-funcs
+          release: 1.86
+          desc: Introspection system for GObject-based libraries
+          homepage: https://wiki.gnome.org/Projects/GObjectIntrospection
+          license: LGPL-2+ GPL-2+
+          iuse: cairo doc doctool
+          required_use: ${PYTHON_REQUIRED_USE}
+          rdepend: |
+            >=dev-libs/{{ .Values.pn }}-common-{{ .Values.version }}
+            dev-libs/glib
+            virtual/libffi:=
+            doctool? ( $(python_gen_cond_dep '
+              dev-python/mako[${PYTHON_USEDEP}]
+              dev-python/markdown[${PYTHON_USEDEP}]
+              ')
+            )
+            virtual/pkgconfig
+            ${PYTHON_DEPS}
+          depend: |
+            ${RDEPEND}
+            doc? ( >=dev-util/gtk-doc-1.19
+              app-text/docbook-xml-dtd:4.3
+              app-text/docbook-xml-dtd:4.5
+            )
+            sys-devel/bison
+            sys-devel/flex
+          body: |
+            pkg_setup() {
+              python-single-r1_pkg_setup
+            }
+            src_prepare() {
+              # we want to configure the various tools to specifically reference the version of python
+              # we are building against. Otherwise, eselect python changes can break gobject-introspection.
+              sed -i -e "/PYTHON_CMD/s:python_cmd:'$PYTHON':" tools/meson.build || die
+              default
+            }
+            src_configure() {
+              local mesonargs=(
+                $(meson_use cairo) \
+                $(meson_use doc gtk_doc) \
+                $(meson_use doctool)
+                -Dpython="${EPYTHON}"
+              )
+              meson_src_configure
+            }
+            src_install() {
+              meson_src_install
+              python_fix_shebang "${ED}"/usr/bin/
+              python_optimize "${ED}"/usr/$(get_libdir)/gobject-introspection/giscanner
+              # Prevent collision with gobject-introspection-common
+              rm -v "${ED}"/usr/share/aclocal/introspection.m4 \
+                "${ED}"/usr/share/gobject-introspection-1.0/Makefile.introspection || die
+              rmdir "${ED}"/usr/share/aclocal || die
+            }
+
+    - gobject-introspection-common:
+        category: dev-libs
+        vars:
+          s: '${WORKDIR}/{{ .Values.tname }}-{{ .Values.version }}'
+          tname: gobject-introspection
+          release: 1.86
+          desc: Build infrastructure for GObject Introspection
+          homepage: https://wiki.gnome.org/Projects/GObjectIntrospection
+          license: HPND
+          body: |
+            src_configure() { :; }
+            src_compile() { :; }
+            src_install() {
+              dodir /usr/share/aclocal
+              insinto /usr/share/aclocal
+              doins m4/introspection.m4
+              dodir /usr/share/gobject-introspection-1.0
+              insinto /usr/share/gobject-introspection-1.0
+              doins Makefile.introspection
+            }
+
+    - glib-utils:
+        category: dev-libs
+        ignore_artefacts: true
+        vars:
+          desc: meta package for glib
+          tname: glib
+          release: 2.86
+          python_compat: ''
+          rdepend: |
+            ~dev-libs/glib-{{ .Values.version }}
+
+    - glib:
+        category: dev-libs
+        vars:
+          release: 2.86
+          slot: 2
+          desc: The GLib library of C routines
+          homepage: https://www.gtk.org/
+          inherit:
+            - meson
+            - bash-completion-r1
+            - flag-o-matic
+            - gnome3
+            - libtool
+            - pax-utils
+            - python-any-r1
+            - toolchain-funcs
+          iuse: dbus fam gtk-doc +mime selinux static-libs systemtap xattr
+          rdepend: |
+            dev-libs/libpcre[static-libs?]
+            virtual/libicon
+            virtual/libffi:=
+            virtual/libintl
+            sys-libs/zlib
+            sys-apps/util-linux
+            selinux? ( sys-libs/libselinux )
+            fam? ( virtual/fam )
+            >=dev-util/gdbus-codegen-{{ .Values.version }}
+            virtual/libelf:0=
+          depend: |
+            ${RDEPEND}
+            app-text/docbook-xsl-stylesheets
+            dev-libs/libxslt
+            sys-devel/gettext
+            gtk-doc? ( dev-util/gtk-doc )
+            systemtap? ( dev-util/systemtap )
+          bdepend: |
+            ${PYTHON_DEPS}
+            virtual/pkgconfig
+          pdepend: |
+            dbus? ( gnome-base/dconf )
+            mime? ( x11-misc/shared-mime-info )
+          body: |
+            pkg_setup() {
+              python-any-r1_pkg_setup
+            }
+            src_prepare() {
+              default
+              # Don't build tests, also prevents extra deps, bug #512022
+              sed -i -e "/subdir('tests')/d" {.,gio,glib}/meson.build || die
+              # gdbus-codegen is a separate package
+              sed -i -e "s/install : true/install : false/" \
+                -i -e "s/install_dir : get_option('bindir')/install_dir : '' /" \
+                -i -e "s/install_dir : codegen_dir/install_dir : '' /" gio/gdbus-2.0/codegen/meson.build
+              sed -i -e "s/[, ]*'gdbus-codegen.*'[,]*//" docs/reference/gio/meson.build
+              # Tarball doesn't come with gtk-doc.make and we can't unconditionally depend on dev-util/gtk-doc due
+              # to circular deps during bootstramp. If actually not building gtk-doc, an almost empty file will do
+              # fine as well - this is also what upstream autogen.sh does if gtkdocize is not found. If gtk-doc is
+              # installed, eautoreconf will call gtkdocize, which overwrites the empty gtk-doc.make with a full copy.
+              echo 'EXTRA_DIST =' > gtk-doc.make
+              echo 'CLEANFILES =' >> gtk-doc.make
+            }
+            src_configure() {
+              # Avoid circular depend with dev-util/pkgconfig and
+              # native builds (cross-compiles won't need pkg-config
+              # in the target ROOT to work here)
+              if ! $(tc-getPKG_CONFIG) --version >& /dev/null; then
+                if has_version sys-apps/dbus; then
+                  export DBUS1_CFLAGS="-I/usr/include/dbus-1.0 -I/usr/$(get_libdir)/dbus-1.0/include"
+                  export DBUS1_LIBS="-ldbus-1"
+                fi
+                export LIBFFI_CFLAGS="-I$(echo /usr/$(get_libdir)/libffi-*/include)"
+                export LIBFFI_LIBS="-lffi"
+                export PCRE_CFLAGS=" " # test -n "$PCRE_CFLAGS" needs to pass
+                export PCRE_LIBS="-lpcre"
+              fi
+              local emesonargs=(
+                -Dc_args="${CFLAGS}"
+                -Dman-pages=enabled
+                -Ddefault_library=$(usex static-libs both shared)
+                $(meson_use xattr)
+                $(meson_use gtk-doc documentation)
+                -Dlibmount=enabled
+                -Dselinux=$(usex selinux enabled disabled)
+                $(meson_feature systemtap dtrace)
+                $(meson_feature systemtap)
+              )
+              meson_src_configure
+            }
+            src_install() {
+              meson_src_install completiondir="$(get_bashcompdir)"
+              keepdir /usr/$(get_libdir)/gio/modules
+              einstalldocs
+              # Do not install charset.alias even if generated, leave it to libiconv
+              rm -f "${ED}/usr/$(get_libdir)/charset.alias"
+              # Don't install gdb python macros, bug 291328
+              rm -rf "${ED}/usr/share/gdb/" "${ED}/usr/share/glib-2.0/gdb/"
+              # Completely useless with or without USE static-libs, people need to use pkg-config
+              find "${ED}" -name '*.la' -delete || die
+            }
+            pkg_preinst() {
+              gnome3_pkg_preinst
+              # Make gschemas.compiled belong to glib alone
+              local cache="usr/share/glib-2.0/schemas/gschemas.compiled"
+              if [[ -e ${EROOT}${cache} ]]; then
+                cp "${EROOT}"${cache} "${ED}"/${cache} || die
+              else
+                touch "${ED}"/${cache} || die
+              fi
+              # Make giomodule.cache belong to glib alone
+              local cache="usr/$(get_libdir)/gio/modules/giomodule.cache"
+              if [[ -e ${EROOT}${cache} ]]; then
+                cp "${EROOT}"${cache} "${ED}"/${cache} || die
+              else
+                touch "${ED}"/${cache} || die
+              fi
+            }
+            pkg_postinst() {
+              # force (re)generation of gschemas.compiled
+              GNOME3_ECLASS_GLIB_SCHEMAS="force"
+              gnome3_pkg_postinst
+            }
+            pkg_postrm() {
+              gnome3_pkg_postrm
+              if [[ -z ${REPLACED_BY_VERSION} ]]; then
+                rm -f "${EROOT}"usr/$(get_libdir)/gio/modules/giomodule.cache
+                rm -f "${EROOT}"usr/share/glib-2.0/schemas/gschemas.compiled
+              fi
+            }
+
+    - pango:
+        category: x11-libs
+        vars:
+          inherit:
+            - flag-o-matic
+            - meson
+            - toolchain-funcs
+            - xdg
+          desc: "Internationalized text layout and rendering library"
+          homepage: "https://www.pango.org/ https://gitlab.gnome.org/GNOME/pango"
+          license: "LGPL-2+"
+          release: 1.57
+          iuse: "debug doc +introspection sysprof X"
+          rdepend: |
+            dev-libs/glib:2
+            dev-libs/fribidi
+            media-libs/harfbuzz:=[glib(+),introspection?,truetype(+)]
+            >=media-libs/fontconfig-2.17.1:1.0=
+            x11-libs/cairo:=[X?]
+            media-libs/freetype:2=
+            introspection? ( >=dev-libs/gobject-introspection-1.83.2:= )
+            X? (
+              x11-libs/libX11
+              x11-libs/libXft
+              x11-libs/libXrender
+            )
+          depend: |
+            ${RDEPEND}
+            sysprof? ( dev-util/sysprof-capture )
+            X? ( x11-base/xorg-proto )
+          bdepend: |
+            dev-util/glib-utils
+            sys-apps/help2man
+            virtual/pkgconfig
+          body: |
+            src_prepare() {
+              xdg_src_prepare
+              export G_HOME="${T}"
+              export GST_REGISTRY="${T}/registry.xml"
+              export GSETTINGS_BACKEND="memory"
+              export GST_INSPECT="$(type -P true)"
+              unset DISPLAY
+            }
+            src_configure() {
+              if use debug; then
+                append-cflags -DPANGO_ENABLE_DEBUG
+              else
+                append-cflags -DG_DISABLE_CAST_CHECKS
+              fi
+              local emesonargs=(
+                --wrap-mode nofallback
+                -Ddocumentation=false
+                -Dbuild-testsuite=false
+                -Dlibthai=disabled
+                -Dcairo=enabled
+                -Dfontconfig=enabled
+                -Dfreetype=enabled
+                $(meson_feature introspection)
+                $(meson_feature sysprof)
+                $(meson_feature X xft)
+              )
+              meson_src_configure
+            }
+            src_install() {
+              meson_src_install
+              if use doc; then
+                insinto /usr/share/gtk-doc/html
+                doins -r "${S}"/docs/Pango*
+              fi
+            }
+            pkg_postinst() {
+              xdg_pkg_postinst
+              if has_version 'media-libs/freetype[-harfbuzz]' ; then
+                ewarn "media-libs/freetype is installed without harfbuzz support. This may"
+                ewarn "lead to minor font rendering problems, see bug 712374."
+              fi
+            }
+
+
+x11_software_dirlisting:
+  generator: builtin-dirlisting
+  template:
+    engine: helm
+
+  defaults:
+    files_dir: "{{ .Values.pn }}"
+    template: ../../templates/simple.tmpl
+    dir:
+      url: 'https://www.freedesktop.org/software/{{ .Values.pn }}/{{ .Values.extra_path | default "" }}'
+      exclude: ".99"
+      matcher: "{{ .Values.pn }}-.*.tar.xz$"
+    transform:
+      - kind: string
+        match: '{{ .Values.pn }}-'
+        replace: ''
+      - kind: string
+        match: '.tar.xz'
+        replace: ''
+    vars:
+      license: MIT
+
+  packages:
+    - desktop-file-utils:
+        category: dev-util
+        vars:
+          extra_path: 'releases/'
+          inherit:
+            - meson
+          desc: Command line utilities to work with desktop menu entries
+          homepage: https://freedesktop.org/wiki/Software/desktop-file-utils/
+          license: GPL-2+
+          rdepend: |
+            dev-libs/glib:2
+          depend: |
+            ${RDEPEND}
+          bdepend: |
+            app-arch/xz-utils
+            virtual/pkgconfig
+          docs:
+            - AUTHORS
+            - ChangeLog
+            - HACKING
+            - NEWS
+            - README
