Merge pull request #1414 in CORE/kit-fixups from ~S4ULIU5/kit-fixups:feature/FL-8746-update-dev-lang-go-to-1.17 to master
Squashed commit of the following:

commit afbefe0776525ed9e73831ceac5479728452fc6c
Author: Saulius Gurklys <s4uliu5@gmail.com>
Date:   Wed Sep 1 08:52:58 2021 +0300

    FL-8746: dev-lang/go: update to 1.17

    Dropped 1.14.x.

diff --git a/lang-kit/curated/dev-lang/templates/go.tmpl b/lang-kit/curated/dev-lang/templates/go.tmpl
--- a/lang-kit/curated/dev-lang/templates/go.tmpl
+++ b/lang-kit/curated/dev-lang/templates/go.tmpl
@@ -22,16 +22,25 @@ HOMEPAGE="https://golang.org"
 
 LICENSE="BSD"
 SLOT="0/${PV}"
+IUSE="cpu_flags_x86_sse2"
 
 BDEPEND="|| (
 		dev-lang/go
 		dev-lang/go-bootstrap )"
+RDEPEND="!<dev-go/go-tools-0_pre20150902"
+
+# the *.syso files have writable/executable stacks
+QA_EXECSTACK='*.syso'
 
 # Do not complain about CFLAGS, etc, since Go doesn't use them.
 QA_FLAGS_IGNORED='.*'
 
 # The tools in /usr/lib/go should not cause the multilib-strict check to fail.
 QA_MULTILIB_PATHS="usr/lib/go/pkg/tool/.*/.*"
+
+# This package triggers "unrecognized elf file(s)" notices on riscv.
+# https://bugs.gentoo.org/794046
+QA_PREBUILT='.*'
 
 # Do not strip this package. Stripping is unsupported upstream and may
 # fail.
@@ -45,19 +54,20 @@ PATENTS
 README.md
 )
 
-go_arch()
-{
+go_arch() {
 	# By chance most portage arch names match Go
 	local portage_arch=$(tc-arch $@)
 	case "${portage_arch}" in
 		x86)	echo 386;;
 		x64-*)	echo amd64;;
+		ppc64) [[ $(tc-endian $@) = big ]] && echo ppc64 || echo ppc64le ;;
+		riscv) echo riscv64 ;;
+		s390) echo s390x ;;
 		*)		echo "${portage_arch}";;
 	esac
 }
 
-go_arm()
-{
+go_arm() {
 	case "${1:-${CHOST}}" in
 		armv5*)	echo 5;;
 		armv6*)	echo 6;;
@@ -68,40 +78,43 @@ go_arm()
 	esac
 }
 
-go_os()
-{
+go_os() {
 	case "${1:-${CHOST}}" in
 		*-linux*)	echo linux;;
+		*-darwin*)	echo darwin;;
+		*-freebsd*)	echo freebsd;;
+		*-netbsd*)	echo netbsd;;
+		*-openbsd*)	echo openbsd;;
+		*-solaris*)	echo solaris;;
+		*-cygwin*|*-interix*|*-winnt*)
+			echo windows
+			;;
 		*)
 			die "unknown GOOS for ${1:-${CHOST}}"
 			;;
 	esac
 }
 
-go_tuple()
-{
+go_tuple() {
 	echo "$(go_os $@)_$(go_arch $@)"
 }
 
-go_cross_compile()
-{
+go_cross_compile() {
 	[[ $(go_tuple ${CBUILD}) != $(go_tuple) ]]
 }
 
-src_compile()
-{
-	# try go-bootstrap first
-	if has_version -b dev-lang/go-bootstrap; then
-		export GOROOT_BOOTSTRAP="${BROOT}/usr/lib/go-bootstrap"
-	elif has_version -b dev-lang/go; then
+src_compile() {
+	if has_version -b dev-lang/go; then
 		export GOROOT_BOOTSTRAP="${BROOT}/usr/lib/go"
+	elif has_version -b dev-lang/go-bootstrap; then
+		export GOROOT_BOOTSTRAP="${BROOT}/usr/lib/go-bootstrap"
 	else
 		eerror "Go cannot be built without go or go-bootstrap installed"
 		die "Should not be here, please report a bug"
 	fi
 
 	export GOROOT_FINAL="${EPREFIX}"/usr/lib/go
-	export GOROOT="$(pwd)"
+	export GOROOT="${PWD}"
 	export GOBIN="${GOROOT}/bin"
 
 	# Go's build script does not use BUILD/HOST/TARGET consistently. :(
@@ -113,16 +126,14 @@ src_compile()
 	export GOOS=$(go_os)
 	export CC_FOR_TARGET=$(tc-getCC)
 	export CXX_FOR_TARGET=$(tc-getCXX)
-	if [[ ${ARCH} == arm ]]; then
-		export GOARM=$(go_arm)
-	fi
+	use arm && export GOARM=$(go_arm)
+	use x86 && export GO386=$(usex cpu_flags_x86_sse2 '' 'softfloat')
 
 	cd src
-	./make.bash || die "build failed"
+	bash -x ./make.bash || die "build failed"
 }
 
-src_test()
-{
+src_test() {
 	go_cross_compile && return 0
 
 	cd src
@@ -133,24 +144,41 @@ src_test()
 	rm -fr pkg/obj/go-build || die
 }
 
-src_install()
-{
-	local bin_path f x
-
+src_install() {
+	# There is a known issue which requires the source tree to be installed [1].
+	# Once this is fixed, we can consider using the doc use flag to control
+	# installing the doc and src directories.
+	# The use of cp is deliberate in order to retain permissions
+	# [1] https://golang.org/issue/2775
 	dodir /usr/lib/go
-
-	# deliberately use cp to retain permissions
 	cp -R api bin doc lib pkg misc src test "${ED}"/usr/lib/go
+	einstalldocs
+
 	# testdata directories are not needed on the installed system
 	rm -fr $(find "${ED}"/usr/lib/go -iname testdata -type d -print)
+
+	local bin_path
 	if go_cross_compile; then
 		bin_path="bin/$(go_tuple)"
 	else
 		bin_path=bin
 	fi
+	local f x
 	for x in ${bin_path}/*; do
 		f=${x##*/}
 		dosym ../lib/go/${bin_path}/${f} /usr/bin/${f}
 	done
-	einstalldocs
+}
+
+pkg_postinst() {
+	[[ -z ${REPLACING_VERSIONS} ]] && return
+	einfo "After ${CATEGORY}/${PN} is updated it is recommended to rebuild"
+	einfo "all packages compiled with previous versions of ${CATEGORY}/${PN}"
+	einfo "due to the static linking nature of go."
+	einfo "If this is not done, the packages compiled with the older"
+	einfo "version of the compiler will not be updated until they are"
+	einfo "updated individually, which could mean they will have"
+	einfo "vulnerabilities."
+	einfo "Run 'emerge @golang-rebuild' to rebuild all 'go' packages"
+	einfo "See https://bugs.gentoo.org/752153 for more info"
 }
