Pull request #2986: FL-11465: HOTFIX add mini-dashboard support to meilisearch
Merge in CORE/kit-fixups from ~INVAKID404/kit-fixups:FL-11465-meilisearch-mini-dashboard-support to master

Squashed commit of the following:

commit dead18388d63d2ce20471f9c75399099ac54ecc2
Author: invakid404 <invakid404@riseup.net>
Date:   Thu Jul 27 01:31:28 2023 +0300

    Add mini-dashboard support to meilisearch

diff --git a/core-server-kit/curated/app-misc/meilisearch/templates/meilisearch.tmpl b/core-server-kit/curated/app-misc/meilisearch/templates/meilisearch.tmpl
--- a/core-server-kit/curated/app-misc/meilisearch/templates/meilisearch.tmpl
+++ b/core-server-kit/curated/app-misc/meilisearch/templates/meilisearch.tmpl
@@ -6,12 +6,16 @@ inherit cargo user
 
 DESCRIPTION="A lightning-fast search engine that fits effortlessly into your apps, websites, and workflow"
 HOMEPAGE="https://www.meilisearch.com/"
-SRC_URI="{{ src_uri }}"
+SRC_URI="
+	{{ artifacts["src"].src_uri }}
+	{{ artifacts["crates_bundle"].src_uri }}
+	mini-dashboard? ( {{ artifacts["mini_dashboard"].src_uri }} )
+"
 
 LICENSE="MIT"
 SLOT="0"
 KEYWORDS="*"
-IUSE=""
+IUSE="+mini-dashboard"
 
 DEPEND=""
 RDEPEND="${DEPEND}"
@@ -23,14 +27,31 @@ S="${WORKDIR}/{{ github_user }}-{{ github_repo }}-{{ sha[:7] }}"
 
 MEILI_DATA_DIR="/var/lib/${PN}"
 
-CARGO_FEATURES=(
-	--no-default-features
-	--features="analytics meilisearch-types/all-tokenizations"
-)
-
 pkg_setup() {
 	enewgroup "${PN}"
 	enewuser "${PN}" -1 -1 "${MEILI_DATA_DIR}" "${PN}"
+}
+
+src_prepare() {
+	default
+
+	if use mini-dashboard; then
+		# Inject path to downloaded mini-dashboard build
+		sed -i "s|{{ mini_dashboard_url }}|${DISTDIR}/{{ artifacts["mini_dashboard"].final_name }}|g" "${S}"/meilisearch/Cargo.toml
+
+		# Replace HTTP fetch with direct file read
+		sed -i -r 's|(let dashboard_assets_bytes =)(.*)$|\1 std::fs::read(url)?;|' "${S}"/meilisearch/build.rs
+	fi
+}
+
+src_configure() {
+	CARGO_FEATURES=(
+		"analytics"
+		"meilisearch-types/all-tokenizations"
+		"$(usex mini-dashboard mini-dashboard '')"
+	)
+
+	default
 }
 
 src_compile() {
@@ -38,11 +59,12 @@ src_compile() {
 	export VERGEN_GIT_SEMVER_LIGHTWEIGHT="${PV}"
 
 	cargo build --release -p meilisearch \
-		"${CARGO_FEATURES[@]}" || die "compile failed"
+		--no-default-features ${CARGO_FEATURES:+--features "${CARGO_FEATURES[*]}"} || die "compile failed"
 }
 
 src_install() {
-	cargo_src_install --path meilisearch --frozen "${CARGO_FEATURES[@]}"
+	cargo_src_install --path meilisearch --frozen \
+		--no-default-features ${CARGO_FEATURES:+--features "${CARGO_FEATURES[*]}"}
 
 	mkdir -p "${ED}"/"${MEILI_DATA_DIR}"
 	pushd "${ED}"/"${MEILI_DATA_DIR}"
