Add_net-libs_accounts-qt_autogen
Add net-libs/accounts-qt autogen

diff --git a/net-kit/autogen.kit.d/base.yml b/net-kit/autogen.kit.d/base.yml
--- a/net-kit/autogen.kit.d/base.yml
+++ b/net-kit/autogen.kit.d/base.yml
@@ -2896,3 +2896,95 @@ openprinting:
                 doinitd "${T}"/cups-browsed
               fi
             }
+
+gitlab_various:
+  generator: builtin-dirlisting
+  defaults:
+    category: net-libs
+    template: ../../templates/simple.tmpl
+    files_dir: "{{ .Values.pn }}"
+    dir:
+      url: 'https://gitlab.com/{{ .Values.gitlab_user }}/{{ .Values.gitlab_repo }}/-/tags'
+    assets:
+      - name: '{{ .Values.pn }}-{{ .Values.version }}.tar.bz2'
+        url: 'https://gitlab.com/{{ .Values.gitlab_user }}/{{ .Values.gitlab_repo }}/-/archive/{{ .Values.original_version }}/{{ .Values.pn }}-{{ .Values.original_version }}.tar.bz2'
+    vars:
+      gitlab_user: accounts-sso
+      homepage: 'https://gitlab.com/{{ .Values.gitlab_user }}/{{ .Values.gitlab_repo }}'
+
+  packages:
+    - accounts-qt:
+        dir:
+          matcher: "/{{ .Values.gitlab_user }}/{{ .Values.gitlab_repo }}/-/tags/VERSION_[0-9.]+"
+        transform:
+          - kind: string
+            match: 'VERSION_'
+            replace: ''
+        vars:
+          gitlab_repo: libaccounts-qt
+          desc: 'Qt6 bindings for libaccounts-glib'
+          homepage: https://gitlab.com/accounts-sso/libaccounts-qt
+          inherit:
+            - qmake-utils
+          iuse: doc
+          s: '${WORKDIR}/{{ .Values.gitlab_repo }}-{{ .Values.original_version }}'
+          keywords: '*'
+          license: LGPL-2.1
+          slot: 0
+          rdepend: |
+            >=net-libs/libaccounts-glib-1.23
+            dev-libs/glib:2
+            dev-qt/qtbase:6
+          bdepend: |
+            doc? (
+                app-doc/doxygen[dot]
+                dev-qt/qttools:6[assistant]
+            )
+          patches:
+                - accounts-qt-1.16-libdir.patch
+          body: |
+            _get_qt6_qmake() {
+                echo "${EPREFIX}/usr/$(get_libdir)/qt6/bin/qmake"
+            }
+            src_prepare() {
+                default
+
+                sed -e "s|share/doc/\$\${PROJECT_NAME}|share/doc/${PF}|" \
+                    -i doc/doc.pri || die
+                sed -e "/QHG_LOCATION/s|qhelpgenerator|${EPREFIX}/usr/$(get_libdir)/qt6/libexec/&|" \
+                    -i doc/doxy.conf || die
+                if ! use doc; then
+                    sed -e "/include( doc\/doc.pri )/d" -i ${PN}.pro || die
+                fi
+                sed -e '/^SUBDIRS/s/tests//' \
+                    -i accounts-qt.pro || die "couldn't disable tests"
+            }
+            src_configure() {
+                $(_get_qt6_qmake) \
+                    -makefile \
+                    QMAKE_AR="$(tc-getAR) cqs" \
+                    QMAKE_CC="$(tc-getCC)" \
+                    QMAKE_LINK_C="$(tc-getCC)" \
+                    QMAKE_LINK_C_SHLIB="$(tc-getCC)" \
+                    QMAKE_CXX="$(tc-getCXX)" \
+                    QMAKE_LINK="$(tc-getCXX)" \
+                    QMAKE_LINK_SHLIB="$(tc-getCXX)" \
+                    QMAKE_OBJCOPY="$(tc-getOBJCOPY)" \
+                    QMAKE_RANLIB= \
+                    QMAKE_STRIP= \
+                    QMAKE_CFLAGS="${CFLAGS}" \
+                    QMAKE_CFLAGS_RELEASE= \
+                    QMAKE_CFLAGS_DEBUG= \
+                    QMAKE_CXXFLAGS="${CXXFLAGS}" \
+                    QMAKE_CXXFLAGS_RELEASE= \
+                    QMAKE_CXXFLAGS_DEBUG= \
+                    QMAKE_LFLAGS="${LDFLAGS}" \
+                    QMAKE_LFLAGS_RELEASE= \
+                    QMAKE_LFLAGS_DEBUG= \
+                    PREFIX="${EPREFIX}"/usr \
+                    LIBDIR=$(get_libdir) \
+                    || die "qmake failed"
+            }
+            src_install() {
+                emake INSTALL_ROOT="${D}" install
+            }
