Pull request #2557: FL-10783: install `code` CLI
Merge in CORE/kit-fixups from ~INVAKID404/kit-fixups:vscode-code-cli to master

Squashed commit of the following:

commit dead930ffe673ee054a040dd68112b4ff7cce1ae
Author: invakid404 <invakid404@riseup.net>
Date:   Fri Dec 2 01:50:33 2022 +0200

    Avoid moving and replacing for stable vscode

commit dead1feb8bf607176f2a4935aa1fb7ff1cd0a73e
Author: invakid404 <invakid404@riseup.net>
Date:   Thu Dec 1 23:34:55 2022 +0200

    Install bash and zsh completions for `code`

commit dead7f470d21cd6ef8a47188d397c84a8e16a73e
Author: invakid404 <invakid404@riseup.net>
Date:   Thu Dec 1 14:35:27 2022 +0200

    Install `code` CLI

diff --git a/editors-kit/curated/app-editors/vscode-bin/templates/vscode-bin.tmpl b/editors-kit/curated/app-editors/vscode-bin/templates/vscode-bin.tmpl
--- a/editors-kit/curated/app-editors/vscode-bin/templates/vscode-bin.tmpl
+++ b/editors-kit/curated/app-editors/vscode-bin/templates/vscode-bin.tmpl
@@ -2,7 +2,7 @@
 
 EAPI=7
 
-inherit desktop eutils pax-utils xdg
+inherit bash-completion-r1 desktop eutils pax-utils xdg
 
 MY_INSTALL_DIR="/opt/${PN}"
 MY_EXEC="{{channel}}"
@@ -32,7 +32,7 @@ LICENSE="
 	W3C"
 SLOT="0"
 KEYWORDS="{{ '*' if unmasked else '' }}"
-IUSE="libsecret hunspell"
+IUSE="libsecret hunspell zsh-completion"
 DEPEND=""
 RDEPEND="
 	hunspell? ( app-text/hunspell )
@@ -69,6 +69,32 @@ pkg_setup() {
 	S="${WORKDIR}/{{ src_path_name }}"
 }
 
+src_prepare() {
+	default
+
+{% if channel != 'code' %}
+	pushd resources/completions
+
+	pushd bash
+	mv "${MY_EXEC}" code || die "bash completion file not found"
+	popd
+
+	if use zsh-completion; then
+		pushd zsh
+		mv _"${MY_EXEC}" _code || die "zsh completion file not found"
+		popd
+	fi
+
+	popd
+
+	sed -i "s/${MY_EXEC}/code/g" resources/completions/bash/code || die "failed to replace in bash completion file"
+
+	if use zsh-completion; then
+		sed -i "s/${MY_EXEC}/code/g" resources/completions/zsh/_code || die "failed to replace in zsh completion file"
+	fi
+{% endif %}
+}
+
 src_install() {
 	pax-mark m "${MY_INSTALL_DIR}/${MY_EXEC}"
 	insinto "${MY_INSTALL_DIR}"
@@ -78,18 +104,29 @@ src_install() {
 	domenu ${FILESDIR}/${PN}.desktop
 	newicon ${S}/resources/app/resources/linux/code.png ${PN}.png
 
+	dosym "${MY_INSTALL_DIR}"/bin/"${MY_EXEC}" "/usr/bin/code"
+
 	fperms +x "${MY_INSTALL_DIR}/${MY_EXEC}"
+	fperms +x "${MY_INSTALL_DIR}/bin/${MY_EXEC}"
+
 	fperms 4755 "${MY_INSTALL_DIR}/chrome-sandbox"
 
-    if [ -e "${ED}"/"${MY_INSTALL_DIR}"/chrome_crashpad_handler ]; then
-        fperms 4755 "${MY_INSTALL_DIR}"/chrome_crashpad_handler
-    fi
+	if [ -e "${ED}"/"${MY_INSTALL_DIR}"/chrome_crashpad_handler ]; then
+		fperms 4755 "${MY_INSTALL_DIR}"/chrome_crashpad_handler
+	fi
 
 	{% for sh_path in fperms_paths|sort -%}
 	fperms +x "${MY_INSTALL_DIR}/{{ sh_path }}"
 	{% endfor -%}
 	insinto "/usr/share/licenses/${PN}"
 	newins "resources/app/LICENSE.rtf" "LICENSE.rtf"
+
+	newbashcomp resources/completions/bash/code code
+
+	if use zsh-completion; then
+		insinto /usr/share/zsh/site-functions
+		doins "${S}"/resources/completions/zsh/_code
+	fi
 }
 
 pkg_postinst() {
