[dev-kit] autogen dev-util/cmake
Keep for now version <4

diff --git a/dev-kit/autogen.kit.d/base.yml b/dev-kit/autogen.kit.d/base.yml
--- a/dev-kit/autogen.kit.d/base.yml
+++ b/dev-kit/autogen.kit.d/base.yml
@@ -575,6 +575,7 @@ dev_github:
   defaults:
     files_dir: "{{ .Values.pn }}"
     template: ../../templates/simple.tmpl
+    category: dev-util
     github:
       query: releases
 
@@ -588,7 +589,6 @@ dev_github:
   packages:
 
     - cbindgen:
-        category: dev-util
         extensions:
           - rust
         github:
@@ -610,8 +610,145 @@ dev_github:
               einstalldocs
             }
 
+    - cmake:
+        template: ../../templates/simple-github.tmpl
+        github:
+          user: Kitware
+          repo: CMake
+        selector:
+          - '<4.0'
+        vars:
+          extra_envs:
+            - 'CMAKE_MAKEFILE_GENERATOR="emake"'
+            - 'CMAKE_REMOVE_MODULES_LIST=( nonde )'
+            - 'SITEFILE="50${PN}-mark.el"'
+          inherit:
+            - bash-completion-r1
+            - cmake
+            - elisp-common
+            - flag-o-matic
+            - multiprocessing
+            - toolchain-funcs
+            - xdg-utils
+          iuse: doc emacs ncurses qt
+          rdepend: |
+            >=app-arch/libarchive-3.3.3:=
+            app-crypt/rhash
+            >=dev-libs/expat-2.0.1
+            >=dev-libs/jsoncpp-1.9.2-r2:0=
+            >=dev-libs/libuv-1.10.0:=
+            >=net-misc/curl-7.21.5[ssl]
+            sys-libs/zlib
+            virtual/pkgconfig
+            emacs? ( >=app-editors/emacs-23.1:* )
+            ncurses? ( sys-libs/ncurses:0= )
+            qt? (
+              || (
+                dev-qt/qtbase:5[gui]
+                dev-qt/qtbase:6[gui]
+              )
+            )
+          depend: '${RDEPEND}'
+          bdepend: |
+            doc? (
+              dev-python/requests
+              dev-python/sphinx
+            )
+          patches:
+            # Keep Gentoo patches for now. I will review the behaviour as second step.
+            - cmake-3.27.0_rc1-0002-Set-some-proper-paths-to-make-cmake-find-our-tools.patch
+            - cmake-3.31.6-Prefer-pkgconfig-in-FindBLAS.patch
+            - cmake-3.27.0_rc1-0004-Ensure-that-the-correct-version-of-Qt-is-always-used.patch
+            - cmake-3.27.0_rc1-0005-Respect-Gentoo-s-Python-eclasses.patch
+            - cmake-3.30.3-cudahostld.patch
+            - cmake-3.31.7-hdf5.patch
+          body: |
+            cmake_src_bootstrap() {
+              # disable running of cmake in bootstrap command
+              sed -i \
+                -e '/"${cmake_bootstrap_dir}\/cmake"/s/^/#DONOTRUN /' \
+                bootstrap || die "sed failed"
+              # bootstrap script isn't exactly /bin/sh compatible
+              tc-env_build ${CONFIG_SHELL:-sh} ./bootstrap \
+                --prefix="${T}/cmakestrap/" \
+                --parallel=$(makeopts_jobs "${MAKEOPTS}" "$(get_nproc)") \
+                || die "Bootstrap failed"
+            }
+            src_prepare() {
+              cmake_src_prepare
+              # Add gcc libs to the default link paths
+              sed -i \
+                -e "s|@GENTOO_PORTAGE_GCCLIBDIR@|${EPREFIX}/usr/${CHOST}/lib/|g" \
+                -e "$(usex prefix-guest "s|@GENTOO_HOST@||" "/@GENTOO_HOST@/d")" \
+                -e "s|@GENTOO_PORTAGE_EPREFIX@|${EPREFIX}/|g" \
+                Modules/Platform/{UnixPaths,Darwin}.cmake || die "sed failed"
+              if ! has_version -b \>=${CATEGORY}/${PN}-3.13 || ! cmake --version &>/dev/null ; then
+                CMAKE_BINARY="${S}/Bootstrap.cmk/cmake"
+                cmake_src_bootstrap
+              fi
+            }
+            src_configure() {
+              # ODR warnings, bug #858335
+              # https://gitlab.kitware.com/cmake/cmake/-/issues/20740
+              filter-flags '-flto*' -fwhole-program-vtables '-fsanitize=cfi*' || die
+
+              local mycmakeargs=(
+              -DCMAKE_USE_SYSTEM_LIBRARIES=ON
+              -DCMake_ENABLE_DEBUGGER=no
+              -DCMAKE_DOC_DIR=/share/doc/${PF}
+              -DCMAKE_MAN_DIR=/share/man
+              -DCMAKE_DATA_DIR=/share/${PN}
+              -DSPHINX_MAN=$(usex doc)
+              -DSPHINX_HTML=$(usex doc)
+              -DBUILD_CursesDialog="$(usex ncurses)"
+              -DBUILD_TESTING=no
+              )
+              use qt && mycmakeargs+=( -DBUILD_QtDialog=ON )
+
+              cmake_src_configure
+            }
+            src_install() {
+              cmake_src_install
+
+              if use emacs; then
+                elisp-install ${PN} Auxiliary/cmake-mode.el Auxiliary/cmake-mode.elc
+                elisp-site-file-install "${FILESDIR}/${SITEFILE}"
+              fi
+
+              insinto /usr/share/vim/vimfiles/syntax
+              doins Auxiliary/vim/syntax/cmake.vim
+
+              insinto /usr/share/vim/vimfiles/indent
+              doins Auxiliary/vim/indent/cmake.vim
+
+              insinto /usr/share/vim/vimfiles/ftdetect
+              doins "${FILESDIR}/${PN}.vim"
+
+              dobashcomp Auxiliary/bash-completion/{${PN},ctest,cpack}
+            }
+
+            pkg_postinst() {
+              use emacs && elisp-site-regen
+
+              if use qt; then
+                xdg_icon_cache_update
+                xdg_desktop_database_update
+                xdg_mimeinfo_database_update
+              fi
+            }
+
+            pkg_postrm() {
+              use emacs && elisp-site-regen
+
+              if use qt; then
+                xdg_icon_cache_update
+                xdg_desktop_database_update
+                xdg_mimeinfo_database_update
+              fi
+            }
+
+
     - go-swagger:
-        category: dev-util
         template: ../../templates/simple-github.tmpl
         extensions:
           - golang
