Pull request #2086: FL-9815: Include dev-db/postgresql into the autogen framework.
Merge in CORE/kit-fixups from ~ALEX2101/kit-fixups:FL-9815-dev-db-postgresql-cve-2021-23214-cve-2021-23222 to master

Squashed commit of the following:

commit 6d185014eee6f0fa6e410113aea5466118b39882
Author: alex2101 <alex2101@gmail.com>
Date:   Tue Jun 21 10:20:00 2022 -0300

    FL-9815: Fix SRC_URI to proper autogen artifacts.

commit 7545cfe793005ea006671fe59f7d1cf61ae68699
Author: alex2101 <alex2101@gmail.com>
Date:   Tue Jun 21 10:14:19 2022 -0300

    FL-9815: Include dev-db/postgresql into the autogen framework.

diff --git a/core-server-kit/curated/dev-db/postgresql/templates/postgresql.tmpl b/core-server-kit/curated/dev-db/postgresql/templates/postgresql.tmpl
--- a/core-server-kit/curated/dev-db/postgresql/templates/postgresql.tmpl
+++ b/core-server-kit/curated/dev-db/postgresql/templates/postgresql.tmpl
@@ -2,26 +2,22 @@
 
 EAPI=7
 
-PYTHON_COMPAT=( python3+ )
+PYTHON_COMPAT=( {{python_compat}} )
 
-inherit flag-o-matic linux-info multilib pam prefix python-single-r1 systemd tmpfiles user
+inherit flag-o-matic linux-info multilib pam prefix python-single-r1 user
 
-KEYWORDS="*"
+KEYWORDS="{{keywords}}"
 
-SLOT=$(ver_cut 1)
-
-MY_PV=${PV/_/}
-S="${WORKDIR}/${PN}-${MY_PV}"
-
-SRC_URI="https://ftp.postgresql.org/pub/source/v${MY_PV}/postgresql-${MY_PV}.tar.bz2"
+SLOT={{slot}}
 
 LICENSE="POSTGRESQL GPL-2"
 DESCRIPTION="PostgreSQL RDBMS"
 HOMEPAGE="https://www.postgresql.org/"
+SRC_URI="{{artifacts[0].src_uri}}"
 
-IUSE="debug doc icu kerberos kernel_linux ldap nls pam perl
-	  python +readline selinux +server systemd ssl static-libs tcl
-	  threads uuid xml zlib"
+IUSE="debug doc icu kerberos ldap{% if slot > 10 %} llvm{% endif %}{% if slot > 13 %} lz4{% endif%} nls pam
+	perl python +readline selinux +server ssl static-libs tcl
+	threads uuid xml zlib"
 
 REQUIRED_USE="python? ( ${PYTHON_REQUIRED_USE} )"
 
@@ -31,12 +27,20 @@ sys-apps/less
 virtual/libintl
 icu? ( dev-libs/icu:= )
 kerberos? ( virtual/krb5 )
-ldap? ( net-nds/openldap )
+ldap? ( net-nds/openldap:= )
+{%- if slot > 10 %}
+llvm? (
+	sys-devel/llvm:=
+	sys-devel/clang:=
+)
+{%- endif %}
+{%- if slot > 13 %}
+lz4? ( app-arch/lz4 )
+{%- endif %}
 pam? ( sys-libs/pam )
 perl? ( >=dev-lang/perl-5.8:= )
 python? ( ${PYTHON_DEPS} )
 readline? ( sys-libs/readline:0= )
-server? ( systemd? ( sys-apps/systemd ) )
 ssl? ( >=dev-libs/openssl-0.9.6-r1:0= )
 tcl? ( >=dev-lang/tcl-8:0= )
 xml? ( dev-libs/libxml2 dev-libs/libxslt )
@@ -46,12 +50,11 @@ zlib? ( sys-libs/zlib )
 # uuid flags -- depend on sys-apps/util-linux for Linux libcs, or if no
 # supported libc in use depend on dev-libs/ossp-uuid. For BSD systems,
 # the libc includes UUID functions.
-UTIL_LINUX_LIBC=( elibc_{glibc,uclibc,musl} )
-BSD_LIBC=( elibc_{Free,Net,Open}BSD )
+UTIL_LINUX_LIBC=( elibc_{glibc,musl} )
 
 nest_usedep() {
 	local front back
-	while [[ ${#} -gt 1 ]]; do
+	while [[ {{ '${#}' }} -gt 1 ]]; do
 		front+="${1}? ( "
 		back+=" )"
 		shift
@@ -59,11 +62,10 @@ nest_usedep() {
 	echo "${front}${1}${back}"
 }
 
-IUSE+=" ${UTIL_LINUX_LIBC[@]} ${BSD_LIBC[@]}"
 CDEPEND+="
 uuid? (
 	${UTIL_LINUX_LIBC[@]/%/? ( sys-apps/util-linux )}
-	$(nest_usedep ${UTIL_LINUX_LIBC[@]/#/!} ${BSD_LIBC[@]/#/!} dev-libs/ossp-uuid)
+	$(nest_usedep ${UTIL_LINUX_LIBC[@]/#/!} dev-libs/ossp-uuid)
 )"
 
 DEPEND="${CDEPEND}
@@ -77,37 +79,40 @@ RDEPEND="${CDEPEND}
 selinux? ( sec-policy/selinux-postgresql )
 "
 
+{%- if patches %}
+PATCHES=(
+{%- for patch in patches %}
+	"${FILESDIR}"/{{patch}}
+{%- endfor %}
+)
+
+{%- endif %}
 pkg_setup() {
-	use server && CONFIG_CHECK="~SYSVIPC" linux-info_pkg_setup
-	use python && python-single-r1_pkg_setup
 	enewgroup postgres 70
 	enewuser postgres 70 /bin/sh /var/lib/postgresql postgres
+	use server && CONFIG_CHECK="~SYSVIPC" linux-info_pkg_setup
+	use python && python-single-r1_pkg_setup
 }
 
 src_prepare() {
 	# Set proper run directory
-	sed "s|\(PGSOCKET_DIR\s\+\)\"/tmp\"|\1\"${EPREFIX}/run/postgresql\"|" \
+	sed -e "s|\(PGSOCKET_DIR\s\+\)\"/tmp\"|\1\"${EPREFIX}/run/postgresql\"|" \
 		-i src/include/pg_config_manual.h || die
 
 	# Rely on $PATH being in the proper order so that the correct
 	# install program is used for modules utilizing PGXS in both
 	# hardened and non-hardened environments. (Bug #528786)
-	sed 's/@install_bin@/install -c/' -i src/Makefile.global.in || die
+	sed -e 's/@install_bin@/install -c/' -i src/Makefile.global.in || die
 
-	use server || eapply "${FILESDIR}/${PN}-10.2-no-server.patch"
+	use server || eapply "${FILESDIR}/${PN}-{{slot}}-no-server.patch"
 
 	if use pam ; then
-		sed -e "s/\(#define PGSQL_PAM_SERVICE \"postgresql\)/\1-${SLOT}/" \
+		sed "s/\(#define PGSQL_PAM_SERVICE \"postgresql\)/\1-${SLOT}/" \
 			-i src/backend/libpq/auth.c || \
 			die 'PGSQL_PAM_SERVICE rename failed.'
 	fi
 
-	# https://bugs.gentoo.org/753257
-	# https://bugs.gentoo.org/766225
-	eapply "${FILESDIR}"/postgresql-10.0-icu68.patch \
-		   "${FILESDIR}"/postgresql-10.0-icu68-2.patch
-
-	eapply_user
+	default
 }
 
 src_configure() {
@@ -127,37 +132,38 @@ src_configure() {
 		for i in ${UTIL_LINUX_LIBC[@]}; do
 			use ${i} && uuid_config="--with-uuid=e2fs"
 		done
-		for i in ${BSD_LIBC[@]}; do
-			use ${i} && uuid_config="--with-uuid=bsd"
-		done
 		[[ -z $uuid_config ]] && uuid_config="--with-uuid=ossp"
 	fi
 
-	econf \
-		--prefix="${PO}/usr/$(get_libdir)/postgresql-${SLOT}" \
-		--datadir="${PO}/usr/share/postgresql-${SLOT}" \
-		--includedir="${PO}/usr/include/postgresql-${SLOT}" \
-		--mandir="${PO}/usr/share/postgresql-${SLOT}/man" \
-		--sysconfdir="${PO}/etc/postgresql-${SLOT}" \
-		--with-system-tzdata="${PO}/usr/share/zoneinfo" \
-		$(use_enable !alpha spinlocks) \
-		$(use_enable debug) \
-		$(use_enable threads thread-safety) \
-		$(use_with icu) \
-		$(use_with kerberos gssapi) \
-		$(use_with ldap) \
-		$(use_with pam) \
-		$(use_with perl) \
-		$(use_with python) \
-		$(use_with readline) \
-		$(use_with ssl openssl) \
-		$(usex server "$(use_with systemd)" '--without-systemd') \
-		$(use_with tcl) \
-		${uuid_config} \
-		$(use_with xml libxml) \
-		$(use_with xml libxslt) \
-		$(use_with zlib) \
+	local myconf=(
+		--prefix="${PO}/usr/$(get_libdir)/postgresql-${SLOT}"
+		--datadir="${PO}/usr/share/postgresql-${SLOT}"
+		--includedir="${PO}/usr/include/postgresql-${SLOT}"
+		--mandir="${PO}/usr/share/postgresql-${SLOT}/man"
+		--sysconfdir="${PO}/etc/postgresql-${SLOT}"
+		--with-system-tzdata="${PO}/usr/share/zoneinfo"
+		$(use_enable !alpha spinlocks)
+		$(use_enable debug)
+		$(use_enable threads thread-safety)
+		$(use_with icu)
+		$(use_with kerberos gssapi)
+		$(use_with ldap)
+		{% if slot > 10 %}$(use_with llvm){% endif %}
+		{% if slot > 13 %}$(use_with lz4){% endif %}
+		$(use_with pam)
+		$(use_with perl)
+		$(use_with python)
+		$(use_with readline)
+		$(use_with ssl openssl)
+		--without-systemd
+		$(use_with tcl)
+		${uuid_config}
+		$(use_with xml libxml)
+		$(use_with xml libxslt)
+		$(use_with zlib)
 		$(use_enable nls)
+	)
+	econf "${myconf[@]}"
 }
 
 src_compile() {
@@ -169,7 +175,7 @@ src_install() {
 	emake DESTDIR="${D}" install
 	emake DESTDIR="${D}" install -C contrib
 
-	dodoc README HISTORY doc/{TODO,bug.template}
+	dodoc README HISTORY
 
 	# man pages are already built, but if we have the target make them,
 	# they'll be generated from source before being installed so we
@@ -246,14 +252,6 @@ src_install() {
 		sed -e "s|@SLOT@|${SLOT}|g" -e "s|@LIBDIR@|$(get_libdir)|g" \
 			"${FILESDIR}/${PN}.init-9.3-r1" | newinitd - ${PN}-${SLOT}
 
-		if use systemd; then
-			sed -e "s|@SLOT@|${SLOT}|g" -e "s|@LIBDIR@|$(get_libdir)|g" \
-				"${FILESDIR}/${PN}.service-9.6-r1" | \
-				systemd_newunit - ${PN}-${SLOT}.service
-			newbin "${FILESDIR}"/${PN}-check-db-dir ${PN}-${SLOT}-check-db-dir
-			newtmpfiles "${FILESDIR}"/${PN}.tmpfiles ${PN}-${SLOT}.conf
-		fi
-
 		use pam && pamd_mimic system-auth ${PN}-${SLOT} auth account session
 
 		if use prefix ; then
@@ -264,7 +262,6 @@ src_install() {
 }
 
 pkg_postinst() {
-	use server && use systemd && tmpfiles_process ${PN}-${SLOT}.conf
 	postgresql-config update
 
 	elog "If you need a global psqlrc-file, you can place it in:"
@@ -378,15 +375,15 @@ pkg_config() {
 
 	einfo "Creating the data directory ..."
 	if [[ ${EUID} == 0 ]] ; then
-		mkdir -p "${DATA_DIR}"
-		chown -Rf postgres:postgres "${DATA_DIR}"
-		chmod 0700 "${DATA_DIR}"
+		mkdir -p "$(dirname ${DATA_DIR%/})" || die "Couldn't parent dirs"
+		mkdir -m 0700 "${DATA_DIR%/}" || die "Couldn't make DATA_DIR"
+		chown -h postgres:postgres "${DATA_DIR%/}" || die "Couldn't chown"
 	fi
 
 	einfo "Initializing the database ..."
 
 	if [[ ${EUID} == 0 ]] ; then
-		su postgres -c "${EROOT}/usr/$(get_libdir)/postgresql-${SLOT}/bin/initdb -D \"${DATA_DIR}\" ${PG_INITDB_OPTS}"
+		su - postgres -c "${EROOT}/usr/$(get_libdir)/postgresql-${SLOT}/bin/initdb -D \"${DATA_DIR}\" ${PG_INITDB_OPTS}"
 	else
 		"${EROOT}"/usr/$(get_libdir)/postgresql-${SLOT}/bin/initdb -U postgres -D "${DATA_DIR}" ${PG_INITDB_OPTS}
 	fi
@@ -412,11 +409,9 @@ pkg_config() {
 	einfo "by default. You can disable it in the cluster's:"
 	einfo "    ${PGDATA%/}/postgresql.conf"
 	einfo
-	if ! use systemd; then
-		einfo "The PostgreSQL server, by default, will log events to:"
-		einfo "    ${DATA_DIR%/}/postmaster.log"
-		einfo
-	fi
+	einfo "The PostgreSQL server, by default, will log events to:"
+	einfo "    ${DATA_DIR%/}/postmaster.log"
+	einfo
 	if use prefix ; then
 		einfo "The location of the configuration files have moved to:"
 		einfo "    ${PGDATA}"
@@ -427,9 +422,6 @@ pkg_config() {
 		einfo
 		einfo "Or move the configuration files back:"
 		einfo "mv ${PGDATA}*.conf ${DATA_DIR}"
-	elif use systemd; then
-		einfo "You should use the 'postgresql-${SLOT}.service' unit to run PostgreSQL"
-		einfo "instead of 'pg_ctl'."
 	else
 		einfo "You should use the '${EROOT}/etc/init.d/postgresql-${SLOT}' script to run PostgreSQL"
 		einfo "instead of 'pg_ctl'."
@@ -438,8 +430,12 @@ pkg_config() {
 
 src_test() {
 	if use server && [[ ${UID} -ne 0 ]] ; then
+		# Some ICU tests fail if LC_CTYPE and LC_COLLATE aren't the same. We set
+		# LC_CTYPE to be equal to LC_COLLATE since LC_COLLATE is set by Portage.
+		local old_ctype=${LC_CTYPE}
+		export LC_CTYPE=${LC_COLLATE}
 		emake check
-
+		export LC_CTYPE=${old_ctype}
 		einfo "If you think other tests besides the regression tests are necessary, please"
 		einfo "submit a bug including a patch for this ebuild to enable them."
 	else
